import os
import json
import pytest
from pathlib import Path
import pandas as pd

from app.validation import ValidationRegistry, DatasetType
from tests.golden_utils import load_golden_dataframe

SNAPSHOTS_DIR = Path(__file__).parent / "snapshots"
UPDATE_SNAPSHOTS = os.environ.get("UPDATE_SNAPSHOTS", "0") == "1"

def assert_snapshot_match(snapshot_name: str, actual_data: dict):
    """
    Compares the `actual_data` dictionary to a frozen snapshot.
    If UPDATE_SNAPSHOTS=1 is set in the environment, it overwrites the snapshot instead.
    """
    SNAPSHOTS_DIR.mkdir(parents=True, exist_ok=True)
    snapshot_path = SNAPSHOTS_DIR / f"{snapshot_name}.json"
    
    if UPDATE_SNAPSHOTS or not snapshot_path.exists():
        with open(snapshot_path, "w", encoding="utf-8") as f:
            json.dump(actual_data, f, indent=4, sort_keys=True)
        # If it didn't exist, we created it. If UPDATE_SNAPSHOTS is true, we updated it.
        # We don't fail the test if we just created/updated it intentionally.
        return

    with open(snapshot_path, "r", encoding="utf-8") as f:
        expected_data = json.load(f)
        
    assert actual_data == expected_data, f"Snapshot mismatch for {snapshot_name}. If this change is intentional, run with UPDATE_SNAPSHOTS=1."

def test_validation_report_snapshot():
    """
    Regression test: Freezes the DataQualityReport generated by the PriceValidator
    when given a healthy dataset. If business logic or metrics change, this will catch it.
    """
    # 1. We mock a healthy dataframe instead of requiring a real golden file to be present right now
    # We will generate a minimal healthy dataframe for testing the snapshot functionality.
    healthy_df = pd.DataFrame({
        "Date": pd.to_datetime(["2023-01-01", "2023-01-02", "2023-01-03"]),
        "Open": [100.0, 101.0, 102.0],
        "High": [105.0, 106.0, 107.0],
        "Low": [95.0, 96.0, 97.0],
        "Close": [102.0, 103.0, 104.0],
        "Volume": [1000, 1100, 1200]
    })
    healthy_df.set_index("Date", inplace=True)
    
    # 2. Get the core Price pipeline
    registry = ValidationRegistry()
    pipeline = registry.get_pipeline(DatasetType.PRICE)
    
    from app.validation.context import ValidationContext
    import dataclasses
    
    # 3. Validate
    context = ValidationContext(provider="YAHOO", interval="1d", period="max")
    result = pipeline.validator.validate(healthy_df, context)
    score = pipeline.score_calculator.calculate(result, context)
    
    # 4. We want to snapshot the observable outcome: The report
    report = {
        "is_valid": result.is_valid,
        "schema_failures": [f.__dict__ for f in result.schema_failures],
        "business_failures": [f.__dict__ for f in result.business_failures],
        "historical_failures": [f.__dict__ for f in result.historical_failures],
        "score": score,
        "metrics": dataclasses.asdict(result.metrics)
    }
    
    # Force stale_days to a constant because it depends on the current date and causes flaky tests
    report["metrics"]["stale_days"] = 0
    
    assert_snapshot_match("price_healthy_validation_report", report)
