from enum import Enum, auto

class ProviderResult(Enum):
    SUCCESS = auto()
    NOT_FOUND = auto()
    RATE_LIMIT = auto()
    NETWORK_ERROR = auto()
    TIMEOUT = auto()
    EMPTY_DATA = auto()
    MARKET_CLOSED = auto()

class MappingState(Enum):
    ACTIVE = auto()
    INVALID = auto()
    TEMP_DISABLED = auto()

class ScannerOutcome(Enum):
    RUNNING = auto()
    SUCCESS = auto()
    PARTIAL_SUCCESS = auto()
    FAILED = auto()
    ABORTED = auto()

class PivotKind(Enum):
    HIGH = "HIGH"
    LOW = "LOW"

class CandidateState(Enum):
    NEW = "NEW"
    PIVOTS_FOUND = "PIVOTS_FOUND"
    IMPULSE_FOUND = "IMPULSE_FOUND"
    PULLBACK_VALID = "PULLBACK_VALID"
    TRIGGER_VALID = "TRIGGER_VALID"
    SCORED = "SCORED"
    SUPPRESSED = "SUPPRESSED"
    ALERTED = "ALERTED"
    REJECTED = "REJECTED"

class RejectionReason(Enum):
    # Eligibility
    REJ_INSUFFICIENT_HISTORY = "REJ_INSUFFICIENT_HISTORY"
    REJ_STALE_DATA = "REJ_STALE_DATA"
    REJ_ILLIQUID = "REJ_ILLIQUID"
    REJ_UNADJUSTED_DATA = "REJ_UNADJUSTED_DATA"
    REJ_PRICE_NAN = "REJ_PRICE_NAN"
    
    # Phase A (Trend)
    REJ_TREND = "REJ_TREND"
    REJ_TREND_FILTERS = "REJ_TREND_FILTERS"
    REJ_RS_NEGATIVE = "REJ_RS_NEGATIVE"
    
    # Phase B (Structure)
    REJ_NO_VALID_IMPULSE = "REJ_NO_VALID_IMPULSE"
    REJ_STRUCTURE_RESET = "REJ_STRUCTURE_RESET"
    REJ_DEPTH_TOO_SHALLOW = "REJ_DEPTH_TOO_SHALLOW"
    REJ_DEPTH_TOO_DEEP = "REJ_DEPTH_TOO_DEEP"
    REJ_DURATION_SHORT = "REJ_DURATION_SHORT"
    REJ_DURATION_LONG = "REJ_DURATION_LONG"
    REJ_DISORDERLY_PULLBACK = "REJ_DISORDERLY_PULLBACK"
    REJ_VOLUME_NOT_CONTRACTING = "REJ_VOLUME_NOT_CONTRACTING"
    REJ_CLOSED_BELOW_SMA50 = "REJ_CLOSED_BELOW_SMA50"
    REJ_RSI_FLOOR = "REJ_RSI_FLOOR"
    
    # Phase C (Trigger)
    REJ_TRIGGER_BEFORE_LOW = "REJ_TRIGGER_BEFORE_LOW"
    REJ_NOT_BULLISH = "REJ_NOT_BULLISH"
    REJ_NO_PRIOR_HIGH_TAKEOUT = "REJ_NO_PRIOR_HIGH_TAKEOUT"
    REJ_WEAK_BODY = "REJ_WEAK_BODY"
    REJ_EXCESSIVE_WICK = "REJ_EXCESSIVE_WICK"
    REJ_GAP_TOO_LARGE = "REJ_GAP_TOO_LARGE"
    REJ_TRIGGER_VOLUME = "REJ_TRIGGER_VOLUME"
    REJ_WEAK_CLOSE = "REJ_WEAK_CLOSE"
    
    # Scoring
    REJ_BASE_SCORE_TOO_LOW = "REJ_BASE_SCORE_TOO_LOW"
    REJ_SCORE = "REJ_SCORE"
    
    # Risk
    REJ_INVALID_STOP = "REJ_INVALID_STOP"
    REJ_INVALID_TARGET = "REJ_INVALID_TARGET"
    REJ_RR = "REJ_RR"
