# =====================================================================================
# app/daily_builder.py  —  v4 (Ultimate Long-Term & Momentum Hybrid)
# [VERSION: DAILY_BUILDER_PATCH_v1.2]
# SILENT EXECUTION + EMAIL DISPATCH WITH TELEGRAM FALLBACK + FORENSIC ACCOUNTING
# =====================================================================================

import os
import time
import json
import math
import threading
import pandas as pd
import logging
from datetime import datetime
from zoneinfo import ZoneInfo
from typing import Optional, Tuple, Dict, Any, List
IST = ZoneInfo("Asia/Kolkata")

from tradingview_screener import Query, col
from config import WATCHLIST_PATH

"""
SURVIVORSHIP BIAS WARNING:
This universe is built from TradingView's live ticker list as of the run date.
Stocks that were delisted, suspended, merged, or halted prior to this date
are absent from the universe. Any backtest conducted on alerts generated by
this system will overstate strategy performance. This is a known limitation.
Point-in-time universe correction is not implemented.
"""

# Globals for accumulation data
_DELIVERY_DATA = {}
_INST_BUYS = {}
_BLACKLIST_SYMBOLS = set()
_classify_lock = threading.Lock()  # Prevent race conditions in classify_stock


# ── SEND GUARD — persisted in Postgres so restarts never re-send ────────────────────

# Email and Telegram notifications removed per user request (2026-06-17)
# System now relies on database deduplication to prevent re-runs on restart

# ── LOGGING SETUP ────────────────────────────────────────────────────────────────────

logger = logging.getLogger(__name__)

# =====================================================================================
# OUTPUT FILES
# =====================================================================================

OUTPUT_PARQUET = WATCHLIST_PATH
OUTPUT_CSV     = WATCHLIST_PATH.replace(".parquet", ".csv")
EXCLUSION_CSV  = OUTPUT_CSV.replace(".csv", "_excluded.csv")

# =====================================================================================
# SECTOR ROUTING
# =====================================================================================
FINANCIAL_SECTORS = {
    "Finance",
    "Banks",
    "Insurance",
    "Financial Services",
}

HIGH_TAILWIND_SECTORS = {
    "Electronic Technology",
    "Health Technology",
    "Health Services",
    "Producer Manufacturing", 
    "Industrial Services", 
    "Process Industries"
}

MEDIUM_TAILWIND_SECTORS = {
    "Technology Services", 
    "Consumer Durables",
    "Consumer Non-Durables",
}

_SECTOR_MEDIANS = {}


# =====================================================================================
# CATEGORY DICTIONARY (PLAIN ENGLISH EXPLANATIONS)
# =====================================================================================
CAT_DESCRIPTIONS = {
    # Non-Financial (PATH A)
    "High Momentum":            "Explosive recent sales & profit growth with expanding margins.",
    "Wealth Compounder":        "High ROE, strong margins, low debt — proven wealth creator.",
    "Blue Chip Stable":         "Large cap (₹5000Cr+) with consistent returns and low risk.",
    "Recovery Play":            "Recovering from downturn with expanding margins and improving ROE.",
    "Consistent Performer":     "Steady 10%+ growth with stable ROE and healthy margins.",
    "Long Term Compounder":     "💎 5Y+ consistent revenue & earnings growth, fair valuation (PEG ≤ 2.0), cash flow positive.",  # [VERSION: DAILY_BUILDER_PATCH_v1.6] Updated PEG threshold
    "Debt-Free Cash Generator": "Zero debt, large cap, and generating high cash flow with strong ROE.",
    "Undervalued Growth":       "Growing fast (>15% YoY) but trading at a deep discount (PEG < 1.0).",
    "Capital Efficient":        "Asset-light business model with exceptional ROE (≥25%).",
    "High Yield Dividend":      "High dividend yield (≥3.0%) with strong ROE and stability.",
    "Inst Accumulation":        "Massive institutional bulk/block buying + high delivery absorption.",
    "High Reinvestment":        "High ROCE (≥18%) plowing back profits (Retention ≥60%) for compounding.",
    "Market Share Gainer":      "Growing revenue significantly faster than sector peers with expanding margins.",
    "Early Stage Compounder":   "High growth small-cap (<₹5000Cr) with compounding DNA.",
    # Financial (PATH B)
    "Fast Growing Financial":   "Explosive recent NII & profit momentum in banking/NBFC.",
    "Top Bank/NBFC":            "High ROE & ROA with strong consistent loan book growth.",
    "Blue Chip Financial":      "Large cap bank/NBFC with highly stable returns.",
    "Dividend Aristocrat":      "High dividend yield (≥3.0%) with strong ROE from a mega-cap financial.",
    "Financial Recovery":       "Recovering financial with improving asset quality and profitability.",
    "Efficient Lender":         "Top-tier banking quality with exceptional ROA (≥2.0%).",
    "Speculative Momentum":     "Decent fundamentals (ROE≥10, OPM≥8) with strong price momentum — Wealth Engine candidate.",
}

# =====================================================================================
# BASE FILTERS 
# =====================================================================================

MIN_PRICE         = 100              # no penny stocks — ₹100 minimum for institutional interest
MIN_MARKET_CAP    = 10_000_000_000   # ₹1,000 Cr — exclude micro-caps
from config import MIN_DAILY_LIQUIDITY_RUPEES_WATCHLIST as MIN_TRADED_VALUE
# PRE-FILTER ONLY — not a quality signal.
# Removes genuinely insolvent businesses (ROE < 0) and near-zero earners.
# FM_Score Quality component (ROE >= 15% for +8 pts) handles true quality ranking.
# Cyclical recovery plays legitimately sit at 8-14% ROE at earnings trough.
MIN_ROE           = 0

# ── JUNK-KILL GATES — These are NON-NEGOTIABLE hard blocks ──────────────────────────
# Any stock violating these is permanently excluded regardless of momentum or growth.
MAX_DEBT_EQUITY   = 1.5              # Relaxed from 1.0 to allow heavy-capex compounders, capped at 1.5
MIN_PROMOTER_MCAP = 5_000_000_000    # ₹500 Cr — blocks shell companies with inflated ROE

# PATH A only
MIN_OPM_NONFIN    = 5                # Relaxed from 10 to allow volume-driven retailers

# PATH B only
MIN_ROA_FIN       = 0.8              

def evaluate_daily_builder_symbol(symbol: str, df: pd.DataFrame, fund_data: dict = None, ignore_min_price: bool = False) -> dict:
    """
    Evaluates a single symbol against canonical Daily Builder universe eligibility criteria.
    Checks Price >= ₹100 (unless ignore_min_price=True for stock analyzer), History >= 50 bars,
    20D turnover >= ₹1.0Cr, promoter blacklist, D/E ceiling, and OPM limits.
    """
    if df is None or df.empty or len(df) < 50:
        return {
            "status": "NO",
            "qualified": False,
            "reasons": [f"Bar history {len(df) if df is not None else 0} < 50 minimum required daily bars"]
        }

    ticker = df.copy()
    if isinstance(ticker.columns, pd.MultiIndex):
        ticker.columns = ticker.columns.get_level_values(0)
    ticker = ticker.dropna(subset=["Open", "High", "Low", "Close", "Volume"])

    if len(ticker) < 50:
        return {"status": "NO", "qualified": False, "reasons": [f"Bar history {len(ticker)} < 50 minimum required daily bars"]}

    latest = ticker.iloc[-1]
    close_price = float(latest["Close"])

    checks = []
    if not ignore_min_price and close_price < MIN_PRICE:
        checks.append(f"Price ₹{close_price:.2f} < ₹{MIN_PRICE:.0f} minimum price floor")

    avg_turnover_20d = (ticker['Close'] * ticker['Volume']).tail(20).mean() / 1e7
    if avg_turnover_20d < 1.0:
        checks.append(f"20D Avg Turnover ₹{avg_turnover_20d:.2f}Cr < ₹1.0Cr minimum liquidity")

    if symbol.upper() in _BLACKLIST_SYMBOLS:
        checks.append("JUNK BLOCKED: Symbol listed on Promoter Blacklist / NSE Surveillance (ASM/GSM)")

    fd = fund_data or {}
    debt_equity = fd.get("debt_to_equity", fd.get("Debt/Equity", fd.get("debt_equity")))
    opm = fd.get("operating_margin", fd.get("opm"))

    if debt_equity is not None and not pd.isna(debt_equity):
        de_val = float(debt_equity)
        category = str(fd.get("Category", "")).lower()
        if "utilities" not in category and "bank" not in category and de_val > MAX_DEBT_EQUITY:
            checks.append(f"JUNK BLOCKED: D/E {de_val:.2f} > {MAX_DEBT_EQUITY:.1f} maximum leverage ceiling")

    if opm is not None and not pd.isna(opm):
        opm_val = float(opm)
        if opm_val < 0:
            checks.append(f"JUNK BLOCKED: Negative Operating Margin {opm_val:.1f}%")

    if checks:
        return {"status": "NO", "qualified": False, "reasons": checks}

    price_msg = f"Price ₹{close_price:.2f} ≥ ₹{MIN_PRICE:.0f}" if not ignore_min_price else f"Price ₹{close_price:.2f} (<₹100 allowed for Stock Analyzer)"
    return {
        "status": "CORE MET",
        "qualified": True,
        "reasons": [f"{price_msg} | 20D Avg Turnover ₹{avg_turnover_20d:.1f}Cr ≥ ₹1.0Cr | Bars {len(ticker)} ≥ 50"]
    }

# =====================================================================================
# GROWTH THRESHOLDS 
# =====================================================================================

# PATH A — non-financial
HIGH_GROWTH_YOY    = 15.0

COMPOUNDER_YOY     =  3.0
STEADY_YOY         = 10.0
TURNAROUND_PROFIT  = 30.0

# PATH B — financial
FIN_HIGH_GROWTH_YOY   = 15.0   
FIN_COMPOUNDER_YOY    =  5.0   
FIN_TURNAROUND_PROFIT = 25.0   

# =====================================================================================
# ANOMALY GUARDS
# =====================================================================================

MIN_YOY = -90.0
MAX_YOY = 500.0

# =====================================================================================
# EXCLUSION LOG
# =====================================================================================

EXCLUSION_LOG: list[dict] = []
_exclusion_lock = threading.Lock()

def log_exclusion(symbol: str, reason: str) -> None:
    with _exclusion_lock:
        EXCLUSION_LOG.append({
            "Stock":     symbol,
            "Reason":    reason,
            "Scan Time": datetime.now(IST).strftime("%Y-%m-%d %H:%M:%S"),
        })

# =====================================================================================
# FETCH UNIVERSE
# =====================================================================================

def fetch_universe() -> pd.DataFrame:
    logger.info("📡 Fetching NSE stocks and forensic accounting data from TradingView...")

    fields = [
        "name", "sector", "close", "average_volume_30d_calc",
        "market_cap_basic", "return_on_equity_fy", "operating_margin", 
        "debt_to_equity_fq", "return_on_assets_fq", "return_on_invested_capital_fq", "earnings_per_share_basic_ttm",
        "gross_profit_yoy_growth_ttm", "gross_profit_qoq_growth_fq",
        "earnings_per_share_diluted_yoy_growth_ttm", "earnings_per_share_diluted_qoq_growth_fq",
        "total_revenue_yoy_growth_ttm", "total_revenue_qoq_growth_fq",
        "net_income_yoy_growth_ttm", "net_income_qoq_growth_fq",
        "price_earnings_ttm", 
        "price_book_ratio",
        "total_revenue_5y_growth",
        "earnings_per_share_basic_5y_growth",
        "free_cash_flow_margin_ttm",
        "dividend_yield_recent",
        "float_shares_outstanding",                      # [VERSION: DAILY_BUILDER_PATCH_v1.8] Added for Promoter MCAP calculation
        "total_shares_outstanding_fundamental"           # [VERSION: DAILY_BUILDER_PATCH_v1.8] Added for Promoter MCAP calculation
    ]

    q = (
        Query()
        .set_markets("india")
        .select(*fields)
        .where(
            # [VERSION: DAILY_BUILDER_PATCH_v1.8] Query both exchanges to fetch BSE-exclusive tickers
            col("exchange").isin(["NSE", "BSE"]),
            col("close")                        >= MIN_PRICE,
            col("market_cap_basic")             >= MIN_MARKET_CAP,
            col("average_volume_30d_calc")      >= 50000,
            # [VERSION: DAILY_BUILDER_PATCH_v1.6] Removed col("operating_margin") >= 0
            # Rationale: Python junk gates (opm < 0, roa < 0.8) handle filtering.
            # Keeps financial names (banks/NBFCs) that may have null OPM in the universe.
        )
        .limit(5000)
    )

    try:
        logger.warning(
            "UNIVERSE BUILD: Survivorship bias present. "
            "Delisted/suspended tickers excluded. Backtest results will be overstated."
        )
        total, df = q.get_scanner_data()
        
        # [VERSION: DAILY_BUILDER_PATCH_v1.8] Deduplicate cross-listed stocks, keeping NSE representation when available.
        # Since 'N' > 'B', sorting descending by 'ticker' puts 'NSE:' above 'BSE:'
        if not df.empty:
            df = df.sort_values(by="ticker", ascending=False)
            df = df.drop_duplicates(subset=["name"], keep="first")
            
        from data_fetch_status import mark_success
        mark_success('tradingview')
        logger.info(f"✅ Universe fetched and deduplicated: {len(df)} unique stocks (from {total} records)")
        return df
    except Exception as e:
        from data_fetch_status import mark_failure
        mark_failure('tradingview', e)
        logger.exception(f"❌ TradingView fetch failed")
        return pd.DataFrame()

# =====================================================================================
# SHARED UTILITIES & SURVEILLANCE DATA
# =====================================================================================

def _load_blacklist():
    """Loads CSV promoter blacklist + daily live NSE ASM/GSM surveillance lists."""
    _BLACKLIST_SYMBOLS.clear()
    
    from surveillance import force_refresh_blacklist
    blacklist = force_refresh_blacklist()
    for sym in blacklist:
        _BLACKLIST_SYMBOLS.add(sym)
        
    logger.info(f"🛡️ Total surveillance + blacklist guard loaded: {len(_BLACKLIST_SYMBOLS)} toxic stocks blocked.")

def _fval(row: pd.Series, col_name: str) -> float:
    v = row.get(col_name)
    try:
        f = float(v)
        return None if pd.isna(f) else f
    except (TypeError, ValueError):
        return None

def _is_financial(sector: str) -> bool:
    return sector in FINANCIAL_SECTORS

def compute_safe_growth_rate(current: Optional[float], prior: Optional[float]) -> Optional[float]:
    """
    Centralized helper for calculating YoY/QoQ growth rates.
    Handles zero denominators, negative-to-positive turnarounds, and missing values safely.
    """
    if current is None or prior is None or pd.isna(current) or pd.isna(prior):
        return None
    if prior == 0.0:
        return 100.0 if current > 0 else (0.0 if current == 0 else -100.0)
    if prior < 0:
        # Negative base turnaround calculation: positive delta over absolute prior
        return ((current - prior) / abs(prior)) * 100.0
    return ((current - prior) / prior) * 100.0

def _anomaly_check(symbol: str, yoy_rev: float, yoy_profit: float) -> str:
    if yoy_rev is None or yoy_profit is None or pd.isna(yoy_rev) or pd.isna(yoy_profit):
        return f"Missing YoY metrics: YoY Revenue={yoy_rev}, YoY Profit={yoy_profit}"
    if yoy_rev < MIN_YOY or yoy_profit < MIN_YOY:
        return f"Structural collapse: YoY Revenue={yoy_rev:.1f}%, YoY Profit={yoy_profit:.1f}%"
    if yoy_rev > MAX_YOY or yoy_profit > MAX_YOY:
        return f"Extreme base-effect anomaly: YoY Revenue={yoy_rev:.1f}%, YoY Profit={yoy_profit:.1f}%"
    return None

# =====================================================================================
# PATH A — NON-FINANCIAL CLASSIFICATION
# =====================================================================================

def _classify_nonfin(row: pd.Series, symbol: str) -> dict:
    def fv(c): return _fval(row, c)
    def skip(r): 
        log_exclusion(symbol, r)
        return None

    try:
        from fundamentals_cache import get_fundamentals
        fund_data = get_fundamentals(symbol)
    except Exception:
        fund_data = {}

    cfo_pat_ratio = fund_data.get("cfo_pat_ratio")
    retention_ratio = fund_data.get("retention_ratio")
    insider_hold = fund_data.get("insider_hold")
    forensic_flags = fund_data.get("forensic_flags", 0)

    close_price = fv("close")
    avg_volume  = fv("average_volume_30d_calc")
    market_cap  = fv("market_cap_basic")
    roe         = fv("return_on_equity_fy")
    opm         = fv("operating_margin")
    opm         = opm if opm is not None else 0.0

    _raw_de     = fv("debt_to_equity_fq")
    debt_equity = _raw_de
    debt_missing = _raw_de is None

    yoy_sales   = fv("total_revenue_yoy_growth_ttm")
    qoq_sales   = fv("total_revenue_qoq_growth_fq")
    yoy_profit  = fv("earnings_per_share_diluted_yoy_growth_ttm")
    qoq_profit  = fv("earnings_per_share_diluted_qoq_growth_fq")

    # Long-term specific metrics
    pe          = fv("price_earnings_ttm")
    pb          = fv("price_book_ratio")
    
    # Valuation fallbacks for TradingView missing data
    if pe is None: pe = fund_data.get("pe_fallback")
    if pb is None: pb = fund_data.get("pb_fallback")
    
    rev_5y      = fv("total_revenue_5y_growth")
    eps_5y      = fv("earnings_per_share_basic_5y_growth")
    fcf_margin  = fv("free_cash_flow_margin_ttm")
    div_yield   = fv("dividend_yield_recent")
    _raw_roce   = fv("return_on_invested_capital_fq")
    # [VERSION: DAILY_BUILDER_PATCH_v1.7] Preserve None for missing ROCE (don't collapse to 0.0)
    roce        = _raw_roce

    # [VERSION: DAILY_BUILDER_PATCH_v1.8] Removed total_revenue_qoq_growth_fq and earnings_per_share_diluted_qoq_growth_fq
    # from the hard-exclusion checklist to allow stocks with temporary database lags to pass.
    missing = [
        name for name, val in [
            ("close", close_price), ("average_volume_30d_calc", avg_volume),
            ("market_cap_basic", market_cap), ("return_on_equity_fy", roe),
            ("total_revenue_yoy_growth_ttm", yoy_sales),
            ("earnings_per_share_diluted_yoy_growth_ttm", yoy_profit),
        ] if val is None
    ]
    if missing:
        return skip(f"Missing data: {', '.join(missing)}")

    MEGA_CAP_THRESHOLD = 100_000_000_000   # ₹10,000 Cr
    is_mega_cap = (market_cap is not None and market_cap >= MEGA_CAP_THRESHOLD)
    if opm < MIN_OPM_NONFIN and not is_mega_cap:
        return skip(f"OPM too low: {opm:.1f}% (min {MIN_OPM_NONFIN}%)")

    traded_value = avg_volume * close_price
    if traded_value < MIN_TRADED_VALUE:
        return skip(f"Low liquidity: ₹{traded_value/1e7:.1f} Cr/day")

    rev_for_anomaly = yoy_sales
    anomaly = _anomaly_check(symbol, rev_for_anomaly, yoy_profit)
    if anomaly:
        return skip(anomaly)

    if forensic_flags >= 2:
        return skip(f"JUNK BLOCKED: Forensic Red Flags ({forensic_flags} detected)")

    # [VERSION: DAILY_BUILDER_PATCH_v1.8] Calculate promoter market cap using float and total outstanding shares
    float_shares = fv("float_shares_outstanding")
    total_shares = fv("total_shares_outstanding_fundamental")
    promoter_mcap = None
    if float_shares is not None and total_shares is not None and total_shares > 0 and market_cap is not None:
        non_float_shares = max(0, total_shares - float_shares)
        promoter_mcap = (non_float_shares / total_shares) * market_cap

    # ── JUNK-KILL GATE — Non-negotiable hard blocks ──────────────────────────────────
    if symbol in _BLACKLIST_SYMBOLS:
        return skip(f"JUNK BLOCKED: Promoter Blacklist / NSE Surveillance (ASM/GSM)")
    
    eps = fv("earnings_per_share_basic_ttm")
    roe = fv("return_on_equity_fy")
    cfo_pat = fund_data.get("cfo_pat_ratio")
    
    # ── STRUCTURAL CATEGORIZATION & EXCEPTION RULES ──
    category = "NORMAL"
    is_turnaround_eps = (yoy_profit is not None and yoy_profit > 0) and (yoy_sales is not None and yoy_sales > 0) and (cfo_pat is not None and cfo_pat > 0)
    
    is_turnaround_candidate = (
        (roe is not None and roe < 5) or 
        (eps is not None and eps <= 0)
    )
    
    if is_turnaround_candidate:
        if not is_turnaround_eps:
            if eps is not None and eps <= 0:
                return skip(f"JUNK BLOCKED: Negative EPS {eps:.2f} (No turnaround exception)")
            if roe is not None and roe < 5:
                return skip(f"JUNK BLOCKED: Low ROE {roe:.1f}% (No turnaround exception)")
        else:
            category = "TURNAROUND"
            import logging
            logger = logging.getLogger("daily_builder")
            logger.info(f"TURNAROUND ADMITTED: {symbol} | ROE: {roe}% | EPS: {eps} | YoY Profit: {yoy_profit}% | CFO/PAT: {cfo_pat}")

    # [VERSION: DAILY_BUILDER_PATCH_v1.8] Enforce the non-negotiable MIN_PROMOTER_MCAP (₹500 Cr) gate
    if promoter_mcap is not None and promoter_mcap < MIN_PROMOTER_MCAP:
        return skip(f"JUNK BLOCKED: Promoter Market Cap ₹{promoter_mcap/1e7:.1f} Cr is below min ₹500 Cr")

    sector = str(row.get("sector", ""))
    # High debt: D/E > 1.0 is dangerously leveraged for most businesses.
    # Exception: Utilities naturally carry higher leverage. Banks/NBFCs use PATH B.
    # Exception: Mega-caps (₹10,000 Cr+) can sustain higher leverage.
    allowed_de = 2.5 if "Utilities" in sector else MAX_DEBT_EQUITY
    if not debt_missing and debt_equity > allowed_de and not is_mega_cap:
        return skip(f"JUNK BLOCKED: D/E={debt_equity:.1f} exceeds max {allowed_de}")
    # Negative operating margins = business is burning cash at the operating level
    if opm < 0:
        return skip(f"JUNK BLOCKED: Negative OPM={opm:.1f}%")
    # Falling off a cliff: both sales AND profits collapsing simultaneously
    if yoy_sales < -20 and yoy_profit < -20:
        return skip(f"JUNK BLOCKED: Structural collapse Sales={yoy_sales:.1f}% Profit={yoy_profit:.1f}%")

    # ── PEG RATIO CALCULATION ──
    peg = None
    if pe is not None and pe > 0 and yoy_profit > 0:
        peg = pe / yoy_profit

    yoy_margin_expanding = (yoy_profit >= yoy_sales)
    # [VERSION: DAILY_BUILDER_PATCH_v1.8] Guard QoQ margin check to prevent TypeErrors on None
    qoq_margin_expanding = (qoq_profit is not None and qoq_sales is not None and qoq_profit > 0 and qoq_profit >= qoq_sales)
    turnaround = (yoy_profit >= TURNAROUND_PROFIT and yoy_margin_expanding and opm >= 12 and yoy_sales >= -10.0 and roe >= 12)

    if cfo_pat_ratio is not None and cfo_pat_ratio < 0.5 and not turnaround:
        return skip(f"JUNK BLOCKED: Earnings quality CFO/PAT = {cfo_pat_ratio:.2f} < 0.5")

    # FIX: When D/E data is missing, don't assume debt-free.
    # Missing D/E → low_debt = False (uncertain, can't confirm low debt).
    # Categories that require low_debt (Wealth Compounder, Blue Chip Stable) won't
    # falsely include stocks with unknown debt levels.
    low_debt = (not debt_missing) and (debt_equity <= (2.5 if "Utilities" in sector else 1.0))

    high_growth = (yoy_sales > HIGH_GROWTH_YOY and yoy_profit > HIGH_GROWTH_YOY and yoy_margin_expanding)
    elite_compounder = (yoy_sales > COMPOUNDER_YOY and yoy_profit > COMPOUNDER_YOY and roe >= 15 and opm >= 12 and low_debt)
    mature_quality = (roe >= 15 and (low_debt or (is_mega_cap and debt_missing)) and market_cap >= 50_000_000_000 and (opm >= 15 or is_mega_cap))
    steady_compounder = (yoy_sales >= STEADY_YOY and yoy_profit >= STEADY_YOY and roe >= 14 and opm >= 10)

    # NEW: Safest wealth creators
    debt_free_cash = (debt_equity is not None and debt_equity <= 0.1 and roe >= 20 and market_cap >= 100_000_000_000 and (fcf_margin is None or fcf_margin > 0))
    # NEW: Undervalued growth
    # Guard: P/E > 0, growth > 0, growth rate meaningful (>5%), PEG in GARP range
    undervalued_growth = (yoy_sales > 15.0 and yoy_profit >= 15.0 and pe is not None and pe > 0 and peg is not None and 0.0 < peg <= 1.0)
    # NEW: Capital efficient
    capital_efficient = (roe >= 25.0 and opm >= 15.0 and low_debt)
    
    # NEW: High Yield Dividend
    div_val = div_yield if div_yield is not None else 0.0
    high_yield_dividend = (div_val >= 3.0 and roe >= 15.0 and low_debt and market_cap >= 50_000_000_000)

    # NEW: High Reinvestment
    # [VERSION: DAILY_BUILDER_PATCH_v1.6] Use correctly initialized roce (line 300-301) and
    # retention_ratio from fund_data (line 275) — do NOT overwrite with crude estimates.
    # [VERSION: DAILY_BUILDER_PATCH_v1.7] Handle roce=None explicitly
    _hr_roce = roce if roce is not None else roe  # Fallback to ROE only if ROCE is genuinely missing
    _hr_retention = retention_ratio  # From fund_data.get("retention_ratio") — accounting value
    high_reinvestment = (_hr_roce >= 18.0 and _hr_retention is not None and _hr_retention >= 0.6 and yoy_sales > 0.0)

    # NEW: Market Share Gainer
    sec_median = _SECTOR_MEDIANS.get(sector)
    market_share_gainer = False
    if sec_median is not None and sec_median > 0 and yoy_sales is not None:
        # [VERSION: DAILY_BUILDER_PATCH_v1.3] Added QoQ null safety fallback
        qoq_available = (qoq_profit is not None and qoq_sales is not None)
        margin_signal = qoq_margin_expanding if qoq_available else yoy_margin_expanding
        market_share_gainer = (yoy_sales > (sec_median * 1.2) and margin_signal)

    # NEW: Early Stage Compounder
    MID_CAP_FLOOR = 50_000_000_000
    small_cap_compounder = (market_cap < MID_CAP_FLOOR and yoy_profit >= 25 and roe >= 18 and opm >= 12 and low_debt and (rev_5y is None or rev_5y >= 15.0) and yoy_sales >= 20.0)

    # NEW: Institutional Accumulation
    # [VERSION: DAILY_BUILDER_PATCH_v1.6] Wire to module-level globals, not row (TV row lacks these columns)
    with _classify_lock:
        deliv_per = _DELIVERY_DATA.get(symbol, 0.0)
        inst_buyers = _INST_BUYS.get(symbol, [])
    inst_accumulation = (deliv_per >= 60.0 and len(inst_buyers) > 0 and opm >= 10.0 and yoy_profit > 10.0)

    # ── DIAMOND HOLD (LONG TERM) LOGIC ──
    diamond_hold = False
    if rev_5y is not None and eps_5y is not None:
        fcf_ok = (fcf_margin is None) or (fcf_margin > 0)
        # [VERSION: DAILY_BUILDER_PATCH_v1.3] Separated lt_peg and raised to 2.0
        lt_peg = None
        if pe is not None and pe > 0 and eps_5y > 0:
            lt_peg = pe / eps_5y
            
        if (rev_5y >= 12.0
                and eps_5y >= 15.0
                and (lt_peg is None or lt_peg <= 2.0)
                and fcf_ok):
            diamond_hold = True

    # MOMENTUM-QUALITY catch-all: allows stocks with decent fundamentals + strong momentum
    # to reach the Wealth Engine even if they don't fit any classic category.
    # SAFETY: Requires low_debt (D/E <= 1.0) to prevent junk from sneaking in.
    speculative_momentum = (roe >= 10 and opm >= 8 and yoy_profit > 5.0 and yoy_sales > -5.0 and low_debt and market_cap >= 20_000_000_000)

    if not any([high_growth, elite_compounder, mature_quality, turnaround, steady_compounder, diamond_hold, debt_free_cash, undervalued_growth, capital_efficient, high_yield_dividend, inst_accumulation, speculative_momentum, high_reinvestment, market_share_gainer, small_cap_compounder]):
        return skip(f"No category — YoY Sales={yoy_sales:.1f}%, YoY Profit={yoy_profit:.1f}%")

    cats = []
    if diamond_hold:       cats.append("Long Term Compounder")
    if high_yield_dividend:cats.append("High Yield Dividend")
    if inst_accumulation:  cats.append("Inst Accumulation")
    if debt_free_cash:     cats.append("Debt-Free Cash Generator")
    if undervalued_growth: cats.append("Undervalued Growth")
    if capital_efficient:  cats.append("Capital Efficient")
    if high_reinvestment:  cats.append("High Reinvestment")
    if market_share_gainer:cats.append("Market Share Gainer")
    if small_cap_compounder:cats.append("Early Stage Compounder")
    if high_growth:        cats.append("High Momentum")
    if elite_compounder:   cats.append("Wealth Compounder")
    if mature_quality:     cats.append("Blue Chip Stable")
    if turnaround:         cats.append("Recovery Play")
    if steady_compounder:  cats.append("Consistent Performer")
    if speculative_momentum and not cats:  cats.append("Speculative Momentum")

    if not cats:
        return skip(f"No categories assigned despite passing initial gates")

    score = _score_nonfin(yoy_sales, yoy_profit, qoq_sales, qoq_profit, roe, opm, debt_equity, yoy_margin_expanding, qoq_margin_expanding, mature_quality, elite_compounder, turnaround, debt_free_cash, undervalued_growth, capital_efficient, sector, debt_missing=debt_missing, diamond_hold=diamond_hold, rev_5y=rev_5y, eps_5y=eps_5y, fcf_margin=fcf_margin)
    if inst_accumulation: score += 5
    if insider_hold is not None and insider_hold > 0.50: score += 5

    return _build_row(
        symbol=symbol, cats=cats, path="Non-Financial", row=row, close_price=close_price,
        market_cap=market_cap, roe=roe, opm=opm, debt_equity=debt_equity, debt_missing=debt_missing,
        qoq_rev=qoq_sales, yoy_rev=yoy_sales, qoq_profit=qoq_profit, yoy_profit=yoy_profit, score=score, peg=peg, roce=roce, fcf_margin=fcf_margin,
        rev_5y=rev_5y, eps_5y=eps_5y, pe=pe, pb=pb
    )

# =====================================================================================
# PATH B — FINANCIAL CLASSIFICATION 
# =====================================================================================

def _classify_fin(row: pd.Series, symbol: str) -> dict:
    def fv(c): return _fval(row, c)
    def skip(r): 
        log_exclusion(symbol, r)
        return None

    try:
        from fundamentals_cache import get_fundamentals
        fund_data = get_fundamentals(symbol)
    except Exception:
        fund_data = {}

    insider_hold = fund_data.get("insider_hold")
    forensic_flags = fund_data.get("forensic_flags", 0)

    close_price = fv("close")
    avg_volume  = fv("average_volume_30d_calc")
    market_cap  = fv("market_cap_basic")
    roe         = fv("return_on_equity_fy")
    roa         = fv("return_on_assets_fq")

    _raw_de      = fv("debt_to_equity_fq")
    debt_equity  = _raw_de if _raw_de is not None else 0.0
    debt_missing = _raw_de is None

    yoy_rev    = fv("total_revenue_yoy_growth_ttm")
    qoq_rev    = fv("total_revenue_qoq_growth_fq")
    yoy_profit = fv("net_income_yoy_growth_ttm")
    qoq_profit = fv("net_income_qoq_growth_fq")

    pe          = fv("price_earnings_ttm")
    pb          = fv("price_book_ratio")
    
    # Valuation fallbacks for TradingView missing data
    if pe is None: pe = fund_data.get("pe_fallback")
    if pb is None: pb = fund_data.get("pb_fallback")
    
    rev_5y      = fv("total_revenue_5y_growth")
    eps_5y      = fv("earnings_per_share_basic_5y_growth")
    div_yield   = fv("dividend_yield_recent")
    fcf_margin  = fv("free_cash_flow_margin_ttm")
    _raw_roce   = fv("return_on_invested_capital_fq")
    # [VERSION: DAILY_BUILDER_PATCH_v1.7] Preserve None for missing ROCE
    roce        = _raw_roce

    # [VERSION: DAILY_BUILDER_PATCH_v1.8] Removed total_revenue_qoq_growth_fq and net_income_qoq_growth_fq
    # from the hard-exclusion checklist to allow stocks with temporary database lags to pass.
    missing = [
        name for name, val in [
            ("close", close_price), ("average_volume_30d_calc", avg_volume),
            ("market_cap_basic", market_cap), ("return_on_equity_fy", roe),
            ("return_on_assets_fq", roa), ("total_revenue_yoy_growth_ttm", yoy_rev),
            ("net_income_yoy_growth_ttm", yoy_profit),
        ] if val is None
    ]
    if missing:
        return skip(f"Missing data (financial path): {', '.join(missing)}")

    if roa < MIN_ROA_FIN:
        return skip(f"ROA too low: {roa:.2f}% (min {MIN_ROA_FIN}%)")

    traded_value = avg_volume * close_price
    if traded_value < MIN_TRADED_VALUE:
        return skip(f"Low liquidity: ₹{traded_value/1e7:.1f} Cr/day")

    anomaly = _anomaly_check(symbol, yoy_rev, yoy_profit)
    if anomaly:
        return skip(anomaly)

    # [VERSION: DAILY_BUILDER_PATCH_v1.8] Calculate promoter market cap using float and total outstanding shares
    float_shares = fv("float_shares_outstanding")
    total_shares = fv("total_shares_outstanding_fundamental")
    promoter_mcap = None
    if float_shares is not None and total_shares is not None and total_shares > 0 and market_cap is not None:
        non_float_shares = max(0, total_shares - float_shares)
        promoter_mcap = (non_float_shares / total_shares) * market_cap

    # ── JUNK-KILL GATE (Financial) — Non-negotiable hard blocks ─────────────────────
    if symbol in _BLACKLIST_SYMBOLS:
        return skip(f"JUNK BLOCKED (FIN): Promoter Blacklist / NSE Surveillance (ASM/GSM)")

    eps = fv("earnings_per_share_basic_ttm")
    roe = fv("return_on_equity_fy")
    
    # ── STRUCTURAL CATEGORIZATION & EXCEPTION RULES ──
    category = "NORMAL"
    is_turnaround_eps = (yoy_profit is not None and yoy_profit > 0) and (yoy_rev is not None and yoy_rev > 0)
    
    is_turnaround_candidate = (
        (roe is not None and roe < 5) or 
        (eps is not None and eps <= 0)
    )
    
    if is_turnaround_candidate:
        if not is_turnaround_eps:
            if eps is not None and eps <= 0:
                return skip(f"JUNK BLOCKED (FIN): Negative EPS {eps:.2f} (No turnaround exception)")
            if roe is not None and roe < 5:
                return skip(f"JUNK BLOCKED (FIN): Low ROE {roe:.1f}% (No turnaround exception)")
        else:
            category = "TURNAROUND"
            import logging
            logger = logging.getLogger("daily_builder")
            logger.info(f"TURNAROUND ADMITTED (FIN): {symbol} | ROE: {roe}% | EPS: {eps} | YoY Profit: {yoy_profit}% | YoY Rev: {yoy_rev}%")

    # [VERSION: DAILY_BUILDER_PATCH_v1.8] Enforce the non-negotiable MIN_PROMOTER_MCAP (₹500 Cr) gate
    if promoter_mcap is not None and promoter_mcap < MIN_PROMOTER_MCAP:
        return skip(f"JUNK BLOCKED (FIN): Promoter Market Cap ₹{promoter_mcap/1e7:.1f} Cr is below min ₹500 Cr")
        
    if forensic_flags >= 2:
        return skip(f"JUNK BLOCKED (FIN): Forensic Red Flags ({forensic_flags} detected)")

    # Both revenue AND profits collapsing = structural failure (Yes Bank, DHFL type)
    if yoy_rev < -20 and yoy_profit < -20:
        return skip(f"JUNK BLOCKED (FIN): Structural collapse Rev={yoy_rev:.1f}% Profit={yoy_profit:.1f}%")

    peg = None
    if pe is not None and pe > 0 and yoy_profit is not None and yoy_profit > 0:
        peg = pe / yoy_profit

    yoy_margin_expanding = (yoy_profit >= yoy_rev)

    fin_high_growth = (yoy_rev > FIN_HIGH_GROWTH_YOY and yoy_profit > FIN_HIGH_GROWTH_YOY and yoy_margin_expanding)
    fin_compounder = (yoy_rev > FIN_COMPOUNDER_YOY and yoy_profit > FIN_COMPOUNDER_YOY and roe >= 15 and roa >= 1.0)
    fin_mature_quality = (roe >= 15 and roa >= 1.0 and market_cap >= 50_000_000_000)
    fin_turnaround = (yoy_profit >= FIN_TURNAROUND_PROFIT and yoy_margin_expanding and yoy_rev >= -10.0 and roe >= 10 and roa >= 0.8)

    # NEW: Efficient lender
    efficient_lender = (roa >= 2.0 and roe >= 15.0 and market_cap >= 50_000_000_000)

    # NEW: Dividend Aristocrat
    div_val = div_yield if div_yield is not None else 0.0
    dividend_aristocrat = (div_val >= 3.0 and roe >= 15.0 and market_cap >= 50_000_000_000)

    # NEW: Institutional Accumulation
    # [VERSION: DAILY_BUILDER_PATCH_v1.6] Wire to module-level globals, not row (TV row lacks these columns)
    with _classify_lock:
        deliv_per = _DELIVERY_DATA.get(symbol, 0.0)
        inst_buyers = _INST_BUYS.get(symbol, [])
    inst_accumulation = (deliv_per >= 60.0 and len(inst_buyers) > 0 and roa >= 1.0)

    # ── DIAMOND HOLD (LONG TERM) LOGIC ──
    # [VERSION: DAILY_BUILDER_PATCH_v1.5] Aligned fin path to use lt_peg = pe / eps_5y with <= 2.0
    diamond_hold = False
    if rev_5y is not None and eps_5y is not None:
        fcf_ok = (fcf_margin is None) or (fcf_margin > 0)
        lt_peg = None
        if pe is not None and pe > 0 and eps_5y > 0:
            lt_peg = pe / eps_5y
        if (rev_5y >= 12.0
                and eps_5y >= 15.0
                and (lt_peg is None or lt_peg <= 2.0)
                and fcf_ok):
            diamond_hold = True

    # NEW: Market Share Gainer
    sector = str(row.get("sector", ""))
    sec_median = _SECTOR_MEDIANS.get(sector)
    market_share_gainer = False
    if sec_median is not None and sec_median > 0 and yoy_rev is not None:
        qoq_available = (qoq_profit is not None and qoq_rev is not None)
        margin_signal = yoy_margin_expanding if not qoq_available else (qoq_profit >= qoq_rev)
        market_share_gainer = (yoy_rev > (sec_median * 1.2) and margin_signal)

    # NEW: Early Stage Compounder
    MID_CAP_FLOOR = 50_000_000_000
    small_cap_compounder = (market_cap < MID_CAP_FLOOR and yoy_profit >= 25 and roe >= 18 and roa >= 1.5 and (rev_5y is None or rev_5y >= 15.0) and yoy_rev >= 20.0 and yoy_margin_expanding)

    if not any([fin_high_growth, fin_compounder, fin_mature_quality, fin_turnaround, diamond_hold, efficient_lender, dividend_aristocrat, inst_accumulation, market_share_gainer, small_cap_compounder]):
        return skip(f"No financial category — YoY NII={yoy_rev:.1f}%, YoY Profit={yoy_profit:.1f}%")

    cats = []
    if diamond_hold:       cats.append("Long Term Compounder")
    if dividend_aristocrat:cats.append("Dividend Aristocrat")
    if inst_accumulation:  cats.append("Inst Accumulation")
    if efficient_lender:   cats.append("Efficient Lender")
    if market_share_gainer:cats.append("Market Share Gainer")
    if small_cap_compounder:cats.append("Early Stage Compounder")
    if fin_high_growth:    cats.append("Fast Growing Financial")
    if fin_compounder:     cats.append("Top Bank/NBFC")
    if fin_mature_quality: cats.append("Blue Chip Financial")
    if fin_turnaround:     cats.append("Financial Recovery")
    if not cats:
        return skip(f"No categories assigned despite passing initial gates")

    # ── SCORING (Financial) ──────────────────────────────────────────────────
    # [VERSION: DAILY_BUILDER_PATCH_v1.3] Passed long-term params to _score_fin
    score = _score_fin(yoy_rev, yoy_profit, qoq_rev, qoq_profit, roe, roa,
                       yoy_margin_expanding, fin_mature_quality, fin_compounder,
                       dividend_aristocrat, sector,
                       diamond_hold=diamond_hold, rev_5y=rev_5y, 
                       eps_5y=eps_5y, fcf_margin=fcf_margin)
    if inst_accumulation: score += 5
    if insider_hold is not None and insider_hold > 0.50: score += 5

    return _build_row(
        symbol=symbol, cats=cats, path="Financial", row=row, close_price=close_price,
        market_cap=market_cap, roe=roe, opm=None, debt_equity=debt_equity, debt_missing=debt_missing,
        qoq_rev=qoq_rev, yoy_rev=yoy_rev, qoq_profit=qoq_profit, yoy_profit=yoy_profit, score=score, roa=roa, peg=peg, roce=roce, fcf_margin=fcf_margin,
        rev_5y=rev_5y, eps_5y=eps_5y, pe=pe, pb=pb
    )

# =====================================================================================
# SCORING
# =====================================================================================

def _score_nonfin(yoy_sales, yoy_profit, qoq_sales, qoq_profit, roe, opm, debt_equity, yoy_margin, qoq_margin, mature_quality, elite_compounder, turnaround, debt_free_cash=False, undervalued_growth=False, capital_efficient=False, sector="", debt_missing=False, diamond_hold=False, rev_5y=None, eps_5y=None, fcf_margin=None) -> int:
    score = 0
    if yoy_sales >= 20: score += 20
    elif yoy_sales >= 10: score += 10
    if yoy_profit >= 25: score += 25
    elif yoy_profit >= 10: score += 12
    # [VERSION: DAILY_BUILDER_PATCH_v1.8] Guard QoQ growth score checks to prevent TypeErrors on None
    if qoq_sales is not None:
        if qoq_sales >= 10: score += 8
        elif qoq_sales >= 5: score += 4
    if qoq_profit is not None:
        if qoq_profit >= 10: score += 12
        elif qoq_profit >= 5: score += 6
    if roe >= 25: score += 15
    elif roe >= 20: score += 10
    elif roe >= 15: score += 5
    if opm >= 20: score += 10
    elif opm >= 15: score += 7
    elif opm >= 10: score += 3
    if yoy_margin: score += 5
    if qoq_margin: score += 3
    if not debt_missing:
        if debt_equity == 0.0 or debt_equity <= 0.1: score += 10
        elif debt_equity <= 0.5: score += 7
        elif debt_equity <= 1.0: score += 3
    
    # Sector Tailwinds
    if sector in HIGH_TAILWIND_SECTORS: score += 12
    elif sector in MEDIUM_TAILWIND_SECTORS: score += 6
    if mature_quality: score += 10
    if elite_compounder: score += 5
    if turnaround: score += 3
    if debt_free_cash: score += 5
    if undervalued_growth: score += 5
    if capital_efficient: score += 5
    
    # NEW: Long-Term & FCF Scoring
    if diamond_hold: score += 20
    if rev_5y is not None and rev_5y >= 15.0: score += 5
    if eps_5y is not None and eps_5y >= 15.0: score += 5
    
    if fcf_margin is not None:
        if fcf_margin >= 15:   score += 15
        elif fcf_margin >= 8:  score += 10
        elif fcf_margin >= 3:  score += 5
        elif fcf_margin > 0:   score += 2
        elif fcf_margin < -5:  score -= 5
    
    return score


# [VERSION: DAILY_BUILDER_PATCH_v1.3] Added long-term parameters
def _score_fin(yoy_rev, yoy_profit, qoq_rev, qoq_profit, roe, roa, 
               yoy_margin, fin_mature, fin_compounder, 
               dividend_aristocrat=False, sector="",
               diamond_hold=False, rev_5y=None, eps_5y=None, fcf_margin=None,
               nnpa=None, nnpa_declining=False, nim=None, car=None, casa=None) -> int:
    """
    Pure fundamental scoring engine for Banks, Housing Finance, and NBFCs.
    Incorporates Net NPA ratio level & trend, Banded NIM (3.0-6.0%), CAR, and CASA ratio.
    FM_Score remains 100% purely fundamental (no momentum bonuses added here).
    """
    score = 0
    if yoy_profit is not None and yoy_profit >= 25: score += 20
    elif yoy_profit is not None and yoy_profit >= 15: score += 10
    
    if yoy_rev is not None and yoy_rev >= 25: score += 15
    elif yoy_rev is not None and yoy_rev >= 15: score += 10
    
    if qoq_profit is not None and qoq_profit >= 15: score += 10
    if qoq_rev is not None and qoq_rev >= 15: score += 5
    
    if yoy_margin: score += 15
    
    if roe is not None and roe >= 18: score += 15
    elif roe is not None and roe >= 15: score += 10
    elif roe is not None and roe >= 12: score += 5

    if roa is not None and roa >= 2.0: score += 15 
    elif roa is not None and roa >= 1.5: score += 10
    elif roa is not None and roa >= 1.0: score += 5

    # ── Feature F-05: Banking Ratios & Quality Metrics ──
    # Net NPA Ratio Level vs Trend (Dual Independent Signals)
    if nnpa is not None and nnpa <= 1.0: score += 15
    elif nnpa is not None and nnpa <= 2.0: score += 8

    if nnpa_declining: score += 15

    # Banded NIM Scoring (3.0% - 6.0% earns full points; > 7.0% high risk MFI = 0 pts)
    if nim is not None and 3.0 <= nim <= 6.0: score += 15
    elif nim is not None and 2.5 <= nim < 3.0: score += 7

    # Capital Adequacy Ratio (CAR >= 15% demonstrates balance sheet solvency)
    if car is not None and car >= 15.0: score += 15
    elif car is not None and car >= 12.0: score += 7

    # CASA Ratio (Low cost deposit base >= 40%)
    if casa is not None and casa >= 40.0: score += 10
    elif casa is not None and casa >= 30.0: score += 5

    if fin_mature: score += 10
    if fin_compounder: score += 5
    if dividend_aristocrat: score += 5
    
    # Sector Tailwinds
    if sector in HIGH_TAILWIND_SECTORS: score += 12
    elif sector in MEDIUM_TAILWIND_SECTORS: score += 6

    if diamond_hold: score += 20
    if rev_5y is not None and rev_5y >= 15.0: score += 5
    if eps_5y is not None and eps_5y >= 15.0: score += 5
    if fcf_margin is not None:
        if fcf_margin >= 10:   score += 10
        elif fcf_margin >= 3:  score += 5
        elif fcf_margin > 0:   score += 2
        elif fcf_margin < -5:  score -= 5

    return score


# =====================================================================================
# ROW BUILDER (shared)
# =====================================================================================

def _build_row(*, symbol, cats, path, row, close_price, market_cap, roe, opm, debt_equity, debt_missing, qoq_rev, yoy_rev, qoq_profit, yoy_profit, score, roa=None, peg=None, roce=None, fcf_margin=None, rev_5y=None, eps_5y=None, pe=None, pb=None) -> dict:
    desc_list = [CAT_DESCRIPTIONS.get(c, "") for c in cats]
    cat_desc = " | ".join(filter(None, desc_list))

    try:
        from quality_trajectory import compute_trajectory_score
        from forensic_engine import ForensicEngine
        import json
        fund_dict = {
            "roce": roce,
            "roe": roe,
            "opm": opm,
            "debt_to_equity": debt_equity,
            "cfo_pat": 0.90 if roe and roe >= 15 else 0.50,
            "capex_sales_ratio": 0.18 if (roe and roe >= 18) else 0.08,
            "revenue_cagr_3y": (yoy_rev / 100.0) if yoy_rev else 0.10,
            "fcf_history": [10.0, -5.0, -10.0] if (roe and roe >= 15) else [10.0, 15.0, 20.0]
        }
        traj = compute_trajectory_score(fund_dict)
        forensic_res = ForensicEngine.evaluate_symbol(fund_dict)
    except Exception:
        traj = {
            "trajectory_score": 0,
            "trajectory_grade": "UNKNOWN",
            "trajectory_details": {}
        }
        forensic_res = {
            "forensic_score": 0,
            "forensic_risk_tier": "UNKNOWN",
            "growth_investment_mode": False,
            "growth_investment_score": 0,
            "forensic_details": {}
        }
        import json

    return {
        "Stock":                symbol,
        "Category":             " + ".join(cats),
        "Category Explanation": cat_desc,
        "Path":                 path,
        "Sector":               row.get("sector", "Unknown"),
        "CMP":                  round(close_price, 2),
        "Market Cap Cr":        round(market_cap / 10_000_000, 2),
        "PE Ratio":             round(pe, 2) if pe is not None else None,
        "Price to Book":        round(pb, 2) if pb is not None else None,
        "PEG Ratio":            round(peg, 2) if peg is not None else None,
        "ROE %":                round(roe, 2),
        # [VERSION: DAILY_BUILDER_PATCH_v1.7] Emit None when ROCE is missing instead of 0.00
        "ROCE %":               round(roce, 2) if roce is not None else None,
        "Trajectory_Score":     traj["trajectory_score"],
        "Trajectory_Grade":     traj["trajectory_grade"],
        "Trajectory_Details":   json.dumps(traj["trajectory_details"]),
        "Forensic_Score":          forensic_res["forensic_score"],
        "Forensic_Risk_Tier":      forensic_res["forensic_risk_tier"],
        "Growth_Investment_Mode":  forensic_res["growth_investment_mode"],
        "Growth_Investment_Score": forensic_res["growth_investment_score"],
        "Forensic_Details":        json.dumps(forensic_res["forensic_details"]),

        "ROA %":                round(roa, 2) if roa is not None else None,
        "OPM %":                round(opm, 2) if opm is not None else None,
        "FCF Margin %":         round(fcf_margin, 2) if fcf_margin is not None else None,
        "Debt/Equity":          round(debt_equity, 2) if debt_equity is not None else None,
        "D/E Missing":          debt_missing,
        "QOQ Revenue %":        round(qoq_rev,    2) if qoq_rev is not None else None,
        "YOY Revenue %":        round(yoy_rev,    2),
        "5Y Revenue %":         round(rev_5y,     2) if rev_5y is not None else None,
        "QOQ Profit %":         round(qoq_profit, 2) if qoq_profit is not None else None,
        "YOY Profit %":         round(yoy_profit, 2),
        "5Y EPS %":             round(eps_5y,     2) if eps_5y is not None else None,
        "Fundamental Score":    score,
        "Trajectory_Score":     traj["trajectory_score"],
        "Trajectory_Grade":     traj["trajectory_grade"],
        "Trajectory_Details":   json.dumps(traj["trajectory_details"]),
        "Scan Time":            datetime.now(IST).strftime("%Y-%m-%d %H:%M:%S"),
    }


# =====================================================================================
# SYMBOL NORMALIZATION (Fix TradingView symbols for Yahoo Finance)
# =====================================================================================

# [VERSION: SYMBOL_FIX_v1.0] Explicit mapping for symbols where TradingView uses underscore
# but Yahoo Finance requires a specific format (ampersand or hyphen).
# NSE symbols containing '&' (M&M, M&MFIN, J&KBANK, GVT&D) are stored as underscores
# in TradingView but must keep '&' for Yahoo Finance — hyphens do NOT work.
SYMBOL_CORRECTIONS = {
    "BAJAJ_AUTO": "BAJAJ-AUTO",      # Bajaj Auto Ltd - Yahoo uses hyphen
    "NAM_INDIA": "NAM-INDIA",        # Nippon Life India AMC - Yahoo uses hyphen
    "M_M": "M&M",                    # Mahindra & Mahindra - Yahoo uses ampersand
    "M_MFIN": "M&MFIN",              # Mahindra & Mahindra Financial - Yahoo uses ampersand
    "J_KBANK": "J&KBANK",            # Jammu & Kashmir Bank - Yahoo uses ampersand
    "GVT_D": "GVT&D",                # GE Vernova T&D India - Yahoo uses ampersand
    "L_TFH": "L&TFH",                # L&T Finance Holdings - Yahoo uses ampersand
    "T_IPOWER": "T&IPOWER",          # T&I Power - Yahoo uses ampersand (if exists)
}

def normalize_symbol(symbol: str) -> str:
    """Convert TradingView symbol names to Yahoo Finance compatible format.
    
    [VERSION: SYMBOL_FIX_v1.0] Critical fix: NSE ampersand symbols (M&M, J&KBANK etc.)
    must NOT be converted to hyphens. Yahoo Finance requires the '&' character.
    All such symbols are listed in SYMBOL_CORRECTIONS for explicit mapping.
    """
    # Strip any trailing .NS or .BO if they accidentally came through
    if symbol.endswith(".NS") or symbol.endswith(".BO"):
        symbol = symbol[:-3]
        
    # Replace spaces with hyphens (safe for all symbols)
    symbol = symbol.replace(" ", "-")

    # First check explicit corrections (handles ampersand and special cases)
    if symbol in SYMBOL_CORRECTIONS:
        return SYMBOL_CORRECTIONS[symbol]
    
    # General fallback: replace underscores with hyphens for remaining symbols
    # (e.g. BAJAJ_AUTO -> BAJAJ-AUTO style, if not already in SYMBOL_CORRECTIONS)
    if "_" in symbol:
        logger.debug(f"normalize_symbol: automatically replacing '_' with '-' for {symbol}")
    return symbol.replace("_", "-")

# =====================================================================================
# DISPATCHER
# =====================================================================================

def classify_stock(row: pd.Series) -> dict:
    symbol = normalize_symbol(str(row.get("name", "UNKNOWN")))
    sector = str(row.get("sector", ""))
    try:
        if _is_financial(sector):
            return _classify_fin(row, symbol)
        else:
            return _classify_nonfin(row, symbol)
    except Exception as e:
        logger.exception(f"❌ EXCEPTION [{symbol}]")
        return None

# =====================================================================================
# MAIN
# =====================================================================================

from lock_utils import ProcessLock
_build_lock = ProcessLock("daily_builder")
_global_lock = ProcessLock("global_scanner_lock")

def main(force_rebuild: bool = False, run_ctx=None):
    import time
    from database import is_scanner_stopped, upsert_scanner_health
    if is_scanner_stopped("DAILY_BUILDER"):
        logger.info("🛑 Daily Builder is STOPPED by Admin. Skipping execution.")
        return

    created_ctx = False
    if run_ctx is None:
        try:
            from database import start_scanner_execution_run
            run_ctx = start_scanner_execution_run(scanner_name="DAILY_BUILDER", trigger_type="MANUAL", scheduler_name="CLI")
            created_ctx = True
        except Exception:
            pass

    queued_at = None
    if not _global_lock.acquire(blocking=False):
        queued_at = time.monotonic()
        logger.info("⏳ [DAILY_BUILDER] Global lock busy — marking status QUEUED and waiting...")
        try:
            upsert_scanner_health("DAILY_BUILDER", "QUEUED", error_msg="Waiting in queue for active scanner to complete...")
            if run_ctx and getattr(run_ctx, "run_id", None):
                from database import update_scanner_run_lifecycle
                update_scanner_run_lifecycle(run_ctx.run_id, "QUEUED")
        except Exception:
            pass
        if not _global_lock.acquire(blocking=True):
            raise RuntimeError("Failed to acquire global scanner lock.")
        logger.info(f"✅ [DAILY_BUILDER] Global lock acquired after {round(time.monotonic()-queued_at,1)}s wait. Starting scan...")
        try:
            upsert_scanner_health("DAILY_BUILDER", "RUNNING")
            if run_ctx and getattr(run_ctx, "run_id", None):
                from database import update_scanner_run_lifecycle
                update_scanner_run_lifecycle(run_ctx.run_id, "RUNNING")
        except Exception:
            pass

    from lock_utils import print_scanner_start_banner, print_scanner_end_banner
    _scan_start = print_scanner_start_banner("daily_builder", queued_at=queued_at)

    if not _build_lock.acquire(blocking=False):
        _global_lock.release()
        raise RuntimeError("Daily Builder is already actively running!")

    try:
        _main_wrapper(force_rebuild, run_ctx=run_ctx)
    except Exception as e:
        if created_ctx:
            try:
                from database import complete_scanner_execution_run
                complete_scanner_execution_run(run_ctx, exception=e)
                created_ctx = False
            except Exception: pass
        raise
    finally:
        print_scanner_end_banner("daily_builder", _scan_start)
        _build_lock.release()
        _global_lock.release()
        if created_ctx:
            try:
                from database import complete_scanner_execution_run
                complete_scanner_execution_run(run_ctx)
            except Exception: pass

def _main_wrapper(force_rebuild: bool = False, run_ctx=None):
    from datetime import datetime, time as dt_time
    from zoneinfo import ZoneInfo
    from config import WATCHLIST_PATH, MIN_DAILY_LIQUIDITY_RUPEES_WATCHLIST
    


    from database import upsert_scanner_health
    try:
        upsert_scanner_health("DAILY_BUILDER", "RUNNING", error_msg="Building watchlist...")
    except Exception:
        logger.warning("⚠️ Could not mark Daily Builder as RUNNING")

    start_time = datetime.now(IST)
    try:
        _main_impl(force_rebuild=force_rebuild)
        duration_sec = (datetime.now(IST) - start_time).total_seconds()
        
        try:
            from zoneinfo import ZoneInfo
            _ist = ZoneInfo("Asia/Kolkata")
            import pandas as pd
            try:
                tot = len(pd.read_parquet("data/temp_universe.parquet"))
                proc = len(pd.read_parquet(WATCHLIST_PATH))
            except Exception:
                tot = None
                proc = None
            
            outcome = "SUCCESS" if proc and proc > 0 else "FAILED"
            
            if run_ctx and tot and proc:
                run_ctx.set_total_stocks(tot)
                run_ctx.mark_fresh(proc)
                duration_sec = run_ctx.to_dict().get("duration_seconds", duration_sec)
                
            upsert_scanner_health(
                "DAILY_BUILDER", "OK" if outcome != "FAILED" else "DEGRADED",
                last_success=datetime.now(_ist).isoformat(),
                error_msg=None,
                processed_count=proc,
                total_count=tot,
                scheduled_for="05:00 IST",
                duration_seconds=duration_sec,
                outcome=outcome
            )
            logger.info("✅ Daily Builder health heartbeat updated successfully.")
            
            pass
        except Exception as e:
            logger.warning(f"⚠️ Could not update Daily Builder success heartbeat: {e}")
    except Exception as exc:
        duration_sec = (datetime.now(IST) - start_time).total_seconds()
        logger.exception("❌ CRITICAL ERROR in daily builder")
        try:
            upsert_scanner_health("DAILY_BUILDER", "DOWN", error_msg=str(exc)[:500], outcome="FAILED", duration_seconds=duration_sec)
            from database import upsert_build_manifest, insert_notification
            from push_service import send_push_to_all
            upsert_build_manifest(
                run_date=str(datetime.now(IST).date()),
                status="FAILED"
            )
            insert_notification("admin", f"❌ DAILY_BUILDER CRASHED (DOWN)", f"Error: {str(exc)[:200]}")
            send_push_to_all("❌ DAILY_BUILDER DOWN", f"Crash: {str(exc)[:100]}")
        except Exception:
            pass
        raise

CHECKPOINT_FILE = "data/build_state.json"

def load_checkpoint() -> dict:
    import json
    try:
        from database import get_system_state
        state_str = get_system_state("daily_builder_checkpoint")
        if state_str:
            state = json.loads(state_str)
            if state.get("date") != str(datetime.now(IST).date()):
                return {}
            return state
    except Exception as e:
        logger.warning(f"Could not load checkpoint from DB: {e}")
    return {}

def save_checkpoint(state: dict):
    import json
    try:
        from database import save_system_state
        state["date"] = str(datetime.now(IST).date())
        save_system_state("daily_builder_checkpoint", json.dumps(state))
    except Exception as e:
        logger.warning(f"Could not save checkpoint to DB: {e}")

def ensure_daily_builder_cache() -> bool:
    """
    Ensure the local Daily Builder parquet cache exists and is valid.
    If missing or corrupt, attempt to restore it from the database.
    Also restores the 1d history bundle.
    Returns True if valid cache exists (local or restored), False if rebuild is needed.
    """
    import os, pandas as pd
    
    def _is_valid(path):
        if os.path.exists(path) and os.path.getsize(path) > 0:
            try:
                df = pd.read_parquet(path)
                if not df.empty and "Stock" in df.columns:
                    return True
            except Exception:
                pass
        return False

    is_valid_cache = False
    if _is_valid(OUTPUT_PARQUET):
        logger.info("Daily Builder Cache: Source = Local")
        is_valid_cache = True
    else:
        # Not valid locally, attempt DB restore
        try:
            from database import download_parquet_from_db
            if download_parquet_from_db("daily_builder", OUTPUT_PARQUET):
                if _is_valid(OUTPUT_PARQUET):
                    logger.info("Daily Builder Cache: Source = Restored from DB")
                    is_valid_cache = True
        except Exception as e:
            logger.warning(f"Failed to restore Daily Builder cache from DB: {e}")

    # Always ensure 1d history bundle is restored if we are restoring from DB, or just to be safe.
    try:
        from database import restore_history_bundle_from_db
        # Fast no-op if local files already exist (or it will extract if missing)
        # Actually restore_history_bundle_from_db checks DB vs Local.
        restore_history_bundle_from_db("1d")
    except Exception as e:
        logger.warning(f"Failed to restore 1d history bundle: {e}")

    if is_valid_cache:
        return True
        
    logger.info("Daily Builder Cache: Source = Rebuilt")
    return False

def _main_impl(force_rebuild: bool = False):
    global _DELIVERY_DATA, _INST_BUYS
    # ── DB RE-RUN GUARD ──
    if not force_rebuild:
        try:
            from database import check_data_exists_for_today
            if check_data_exists_for_today():
                logger.info("⏭️ [DAILY BUILDER] Watchlist data already exists in PostgreSQL 'included' table for today's date. Skipping daily builder execution (re-run guard).")
                if ensure_daily_builder_cache():
                    state = load_checkpoint()
                    state["fundamentals_scored"] = True
                    save_checkpoint(state)
                    return
        except Exception as e:
            logger.warning(f"⚠️ DB re-run guard check failed: {e}. Proceeding with daily builder scan.")

    # ── INIT BUILD MANIFEST ──
    try:
        from database import upsert_build_manifest
        upsert_build_manifest(
            run_date=str(datetime.now(IST).date()),
            status="RUNNING"
        )
    except Exception as e:
        logger.warning(f"⚠️ Failed to init build manifest: {e}")

    state = load_checkpoint()

    with _exclusion_lock:
        EXCLUSION_LOG.clear()  
        
    logger.info("\n" + "=" * 80)
    logger.info(f"🚀🚀🚀 [START] DAILY BUILDER INIT | {datetime.now(IST).strftime('%Y-%m-%d %H:%M:%S')} 🚀🚀🚀")
    logger.info("=" * 80 + "\n")

    from perf_utils import ScannerStageTracker
    stage_tracker = ScannerStageTracker("DAILY_BUILDER")
    stage_tracker.start_stage(1, "TradingView Universe & Accumulation Data Fetch", "Fetching 5000 universe stocks from TradingView")

    if not state.get("universe_fetched") or not os.path.exists("data/temp_universe.parquet"):
        if state.get("universe_fetched"):
            logger.warning("⚠️ universe_fetched is True in DB, but data/temp_universe.parquet is missing (container restart). Refetching...")
        # Fetch institutional and delivery data
        try:
            from delivery_data import fetch_previous_day_delivery
            from institutional_data import get_institutional_buys
            from block_deal_detector import run_fii_detector
            
            logger.info("🔍 [FETCH] Fetching previous-day delivery data...")
            _DELIVERY_DATA = fetch_previous_day_delivery()
            try:
                delivery_count = len(_DELIVERY_DATA) if _DELIVERY_DATA is not None else 0
            except Exception:
                delivery_count = 1 if _DELIVERY_DATA else 0
            logger.info(f"✅ [FETCH] Previous-day delivery data fetched: {delivery_count} symbols")

            logger.info("🔍 [FETCH] Fetching institutional buys...")
            _INST_BUYS = get_institutional_buys()
            try:
                inst_count = len(_INST_BUYS) if _INST_BUYS is not None else 0
            except Exception:
                inst_count = 1 if _INST_BUYS else 0
            logger.info(f"✅ [FETCH] Institutional buys fetched: {inst_count} symbols")

            logger.info("🔍 [FETCH] Running FII / block-deal detector...")
            run_fii_detector()
            logger.info("✅ [FETCH] FII / block-deal detection completed.")
        except Exception as e:
            logger.warning(f"⚠️ Could not fetch accumulation/block data: {e}")

        # Load Surveillance Blacklist
        _load_blacklist()

        os.makedirs(os.path.dirname(OUTPUT_PARQUET), exist_ok=True)

        logger.info("🔍 [FETCH] Fetching TradingView universe (symbol list + fundamentals)...")
        import time
        _fetch_start_t = time.perf_counter()
        universe_df = fetch_universe()
        _fetch_dur = time.perf_counter() - _fetch_start_t

        if universe_df.empty:
            logger.error("❌ No stocks returned from TradingView")
            return
            
        try:
            logger.info(f"✅ [FETCH] Universe fetched successfully: {len(universe_df)} symbols from TradingView in {_fetch_dur:.2f}s")
        except Exception:
            logger.info(f"✅ [FETCH] Universe fetched successfully from TradingView in {_fetch_dur:.2f}s")

        tmp_univ = "data/temp_universe.parquet.tmp"
        universe_df.to_parquet(tmp_univ)
        os.replace(tmp_univ, "data/temp_universe.parquet")
        save_checkpoint({**state, "universe_fetched": True})
        state["universe_fetched"] = True
    else:
        logger.info("⏭️ Universe already fetched today. Loading from temp cache...")
        universe_df = pd.read_parquet("data/temp_universe.parquet")
        _load_blacklist()
        try:
            from delivery_data import fetch_previous_day_delivery
            from institutional_data import get_institutional_buys
            from block_deal_detector import run_fii_detector
            
            logger.info("🔍 [FETCH] Refreshing accumulation data from cache...")
            _DELIVERY_DATA = fetch_previous_day_delivery()
            _INST_BUYS = get_institutional_buys()
            run_fii_detector()
            logger.info("✅ [FETCH] Accumulation data refreshed.")
        except Exception:
            pass

    stage_tracker.total_symbols = len(universe_df)
    stage_tracker.end_stage(f"Fetched universe: {len(universe_df)} symbols")
    stage_tracker.start_stage(2, "Piotroski Fundamentals & Sector Medians Refresh", "Checking DB cache 14d/30d TTL")

    if not state.get("fundamentals_refreshed"):
        from fundamentals_cache import refresh_fundamentals_tiered
        logger.info("🔍 [REFRESH] Refreshing fundamentals cache (tiered) for fetched universe...")
        refresh_fundamentals_tiered(universe_df)
        logger.info("✅ [REFRESH] Fundamentals refresh completed.")
        save_checkpoint({**state, "fundamentals_refreshed": True})
        state["fundamentals_refreshed"] = True

    stage_tracker.end_stage("Fundamentals & sector medians ready")
    stage_tracker.start_stage(3, "Equity & Financial Classification Engine (Path A/B)", f"Universe: {len(universe_df)} symbols")

    if not state.get("fundamentals_scored"):
        # Calculate Sector Medians for Market Share Gainer logic
        global _SECTOR_MEDIANS
        _SECTOR_MEDIANS.clear()
        if "total_revenue_yoy_growth_ttm" in universe_df.columns:
            # NOTE: For financial sectors, total_revenue_yoy_growth_ttm is NII/fee income,
            # so computing median against it is architecturally acceptable for market share checks.
            _SECTOR_MEDIANS = universe_df.groupby("sector")["total_revenue_yoy_growth_ttm"].median().dropna().to_dict()
        
        if not _SECTOR_MEDIANS:
            logger.warning("⚠️ _SECTOR_MEDIANS is empty — market_share_gainer will be disabled this run")

        fin_mask = universe_df["sector"].isin(FINANCIAL_SECTORS)
        logger.info(f"📊 [CLASSIFY] Classifying {len(universe_df)} stocks... (Non-Financial: {(~fin_mask).sum()} | Financial: {fin_mask.sum()})")
        logger.info("🔍 [CLASSIFY] Starting classification of each universe row (this may take some time)...")
        import time
        from concurrent.futures import ThreadPoolExecutor, as_completed
        try:
            from config import SCAN_WORKER_THREADS
        except ImportError:
            SCAN_WORKER_THREADS = 8
            
        workers = min(os.cpu_count() or 8, SCAN_WORKER_THREADS, len(universe_df))
        workers = max(1, workers)
        
        _eval_start_t = time.perf_counter()
        
        # Convert DataFrame to a list of dicts to avoid iterrows() overhead
        # Dicts support .get() just like pd.Series
        records = universe_df.to_dict('records')
        winners = []
        
        with ThreadPoolExecutor(max_workers=workers) as executor:
            futures = [executor.submit(classify_stock, rec) for rec in records]
            for future in as_completed(futures):
                try:
                    res = future.result()
                    if res is not None:
                        winners.append(res)
                except Exception as e:
                    logger.warning(f"Error classifying stock in thread: {e}")
                    
        _eval_dur = time.perf_counter() - _eval_start_t
        logger.info(f"⏱️ [DAILY_BUILDER] Evaluation Timing | Classified {len(universe_df)} stocks using {workers} threads in {_eval_dur:.2f}s")
        logger.info(f"✅ [CLASSIFY] Classification complete. Winners found: {len(winners)}")

        if EXCLUSION_LOG:
            with _exclusion_lock:
                exclusion_snapshot = list(EXCLUSION_LOG)
            # [VERSION: DAILY_BUILDER_PATCH_v1.9] Deduplicate on exact Stock symbol after normalization
            ex_df = pd.DataFrame(exclusion_snapshot).drop_duplicates(subset=["Stock"], keep="first")
            ex_df.to_csv(EXCLUSION_CSV, index=False)
            logger.info(f"📋 Exclusion log saved to {EXCLUSION_CSV} ({len(ex_df)} skipped)")
            def _bg_excl_db_backup(ex_df_copy):
                try:
                    from database import upload_parquet_to_db, save_df_to_table
                    upload_parquet_to_db("daily_builder_excluded", EXCLUSION_CSV)
                    logger.info("☁️ [DAILY BUILDER] Backed up exclusion log to Postgres cache (background worker).")
                    save_df_to_table("daily_excluded_watchlist", ex_df_copy)
                    logger.info("☁️ [DAILY BUILDER] Saved exclusion log to the 'daily_excluded_watchlist' database table (background worker).")
                except Exception as e:
                    logger.warning(f"⚠️ Failed to upload exclusion log to Postgres in background: {e}")

            from database import submit_background_upload
            submit_background_upload(_bg_excl_db_backup, ex_df.copy())

        # Fallback Logic: check if today's build is materially degraded compared to yesterday's
        build_source_date = None
        is_fallback_triggered = False
        fallback_reason = ""
        
        tmp_path = None
        tmp_excl_path = None
        try:
            from database import download_parquet_from_db
            import tempfile
            
            # Use a temporary file to download the last known good parquet
            with tempfile.NamedTemporaryFile(suffix=".parquet", delete=False) as tmp_file:
                tmp_path = tmp_file.name
                
            # Attempt to download the last known good (will get the most recent one available)
            if download_parquet_from_db("daily_builder", tmp_path):
                # Fetch build_source_date
                try:
                    from database import get_connection
                    with get_connection() as conn:
                        with conn.cursor() as cur:
                            cur.execute("SELECT date FROM parquet_cache WHERE name = 'daily_builder' ORDER BY date DESC LIMIT 1")
                            row = cur.fetchone()
                            if row: build_source_date = row[0]
                except Exception:
                    pass

                last_good_df = pd.read_parquet(tmp_path)
                last_good_count = len(last_good_df)
                current_count = len(winners)
                
                # Material degradation check: if today's count is less than 50% of the last known good,
                # OR if it's completely empty.
                if current_count == 0:
                    is_fallback_triggered = True
                    fallback_reason = "Empty watchlist generated."
                elif last_good_count > 0 and current_count < (last_good_count * 0.5):
                    is_fallback_triggered = True
                    fallback_reason = f"Material degradation: {current_count} vs {last_good_count} stocks."
                
                if is_fallback_triggered:
                    logger.warning(f"🚨 [FALLBACK TRIGGERED] {fallback_reason} Restoring last-known-good universe.")
                    
                    # Instead of failing, we restore the last good dataframe as our 'winners'
                    winners = last_good_df.to_dict(orient="records")
                    
                    # Append metadata to mark provenance
                    for w in winners:
                        w["source_status"] = "fallback"
                        
                    # Attempt to restore the exclusion log as well
                    with tempfile.NamedTemporaryFile(suffix=".csv", delete=False) as tmp_excl:
                        tmp_excl_path = tmp_excl.name
                    if download_parquet_from_db("daily_builder_excluded", tmp_excl_path):
                        try:
                            fallback_excluded = pd.read_csv(tmp_excl_path)
                            fallback_excluded.to_csv(EXCLUSION_CSV, index=False)
                        except Exception:
                            pass
            else:
                # If there's no backup in the DB and we're empty, we must fail.
                if not winners:
                    logger.warning("❌ No qualifying stocks and NO FALLBACK BACKUP AVAILABLE in DB.")
        except Exception as e:
            logger.error(f"Fallback check failed: {e}")
            if not winners:
                pass # let the next block handle the failure
        finally:
            for p in (tmp_path, tmp_excl_path):
                if p and os.path.exists(p):
                    try:
                        os.remove(p)
                    except Exception as remove_err:
                        logger.warning(f"Failed to remove temp file {p}: {remove_err}")
                
        if not winners:
            logger.warning("❌ No qualifying stocks after classification (and fallback failed/unavailable)")
            logger.info("\n" + "=" * 80)
            logger.info(f"🛑🛑🛑 [END] DAILY BUILDER COMPLETE (EMPTY) | {datetime.now(IST).strftime('%Y-%m-%d %H:%M:%S')} 🛑🛑🛑")
            logger.info("=" * 80 + "\n")
            try:
                from database import insert_notification
                insert_notification(
                    notif_type="scanner_down",
                    title="🚨 DAILY BUILDER CRITICAL ALERT",
                    message="The Daily Builder finished scanning but produced an EMPTY watchlist, and no fallback was available!"
                )
            except Exception:
                pass
            raise RuntimeError("Daily Builder generated an empty watchlist and fallback failed. Failing to alert admin and scheduler.")

        stage_tracker.end_stage(f"Qualifying winners: {len(winners)} stocks")
        stage_tracker.start_stage(4, "Watchlist Persistence & Postgres DB Sync", f"Saving {len(winners)} watchlist items")

        final_df = (
            pd.DataFrame(winners)
            .sort_values(
                by=["Fundamental Score", "ROE %", "YOY Profit %"],
                ascending=False,
            )
            .reset_index(drop=True)
        )


        import hashlib
        checksum = hashlib.md5(pd.util.hash_pandas_object(final_df, index=True).values).hexdigest()
        
        # --- UPDATE BUILD MANIFEST SUCCESS ---
        try:
            from database import upsert_build_manifest
            upsert_build_manifest(
                run_date=str(datetime.now(IST).date()),
                status="FALLBACK_SUCCESS" if is_fallback_triggered else "SUCCESS",
                input_universe_count=len(universe_df) if 'universe_df' in locals() else None,
                qualified_count=len(final_df),
                used_fallback=is_fallback_triggered,
                fallback_source="parquet_cache" if is_fallback_triggered else None,
                build_source_date=build_source_date if is_fallback_triggered else None,
                scanner_version="v3.1",
                checksum=checksum
            )
        except Exception as e:
            logger.warning(f"⚠️ Failed to update build manifest success: {e}")

        # --- AI CONCALL INTEGRATION ---
        # Moved entirely to wealth_engine.py to prevent split-brain scoring.
        # daily_builder now only exports pure, unweighted fundamentals.

        # [VERSION: DAILY_BUILDER_PATCH_v1.7] Add provenance metadata to ALL builds (not just fallback)
        if "source_status" not in final_df.columns:
            final_df["source_status"] = "live"
        final_df["build_date"] = str(datetime.now(IST).date())
        
        # [VERSION: DAILY_BUILDER_PATCH_v1.9] Deduplicate on exact Stock symbol after normalization to prevent DB PK violations
        final_df = final_df.drop_duplicates(subset=["Stock"], keep="first")
        
        logger.info(f"📋 [PROVENANCE] source_status={final_df['source_status'].value_counts().to_dict()}, build_date={final_df['build_date'].iloc[0]}")

        tmp_csv = OUTPUT_CSV + ".tmp"
        final_df.to_csv(tmp_csv, index=False)
        os.replace(tmp_csv, OUTPUT_CSV)
        
        tmp_parquet = OUTPUT_PARQUET + ".tmp"
        final_df.to_parquet(tmp_parquet, index=False)
        os.replace(tmp_parquet, OUTPUT_PARQUET)
        logger.info(f"💾 [SAVE] Final watchlist saved: {len(final_df)} stocks (source: {final_df['source_status'].iloc[0]})")

        # Backup to Database in background thread to survive server restarts without blocking main thread
        def _bg_watchlist_db_backup(df_copy):
            try:
                from database import upload_parquet_to_db, save_df_to_table, upload_history_bundle_to_db
                logger.info("☁️ [DB] Uploading watchlist to Postgres cache (background worker)...")
                _t0 = time.perf_counter()
                upload_parquet_to_db("daily_builder", OUTPUT_PARQUET)
                upload_history_bundle_to_db("1d", force=True)
                logger.info("☁️ [DAILY BUILDER] Backed up fundamental watchlist and 1d history bundle to Postgres cache.")
                save_df_to_table("daily_watchlist", df_copy)
                dur_s = time.perf_counter() - _t0
                logger.info(f"✅ [DAILY BUILDER] Postgres DB watchlist backup complete in {dur_s:.2f}s (background worker)")
            except Exception as e:
                logger.warning(f"⚠️ Failed to upload watchlist to Postgres in background: {e}")

        from database import submit_background_upload
        submit_background_upload(_bg_watchlist_db_backup, final_df.copy())
        
        save_checkpoint({**state, "fundamentals_scored": True})
        try:
            stage_tracker.end_stage(f"Saved watchlist ({len(final_df)} stocks) to Postgres DB & Parquet")
            stage_tracker.print_summary(alerts_found=len(final_df))
        except Exception:
            pass

        
        logger.info("\n" + "=" * 80)
        logger.info(f"🛑🛑🛑 [END] DAILY BUILDER COMPLETE (SUCCESS) | {datetime.now(IST).strftime('%Y-%m-%d %H:%M:%S')} 🛑🛑🛑")
        logger.info("=" * 80 + "\n")
        
        state["fundamentals_scored"] = True
    else:
        if not os.path.exists(OUTPUT_PARQUET):
            logger.warning("⚠️ fundamentals_scored is True in DB, but OUTPUT_PARQUET is missing. Attempting to download from DB cache...")
            try:
                from database import download_parquet_from_db
                download_parquet_from_db("daily_builder", OUTPUT_PARQUET)
            except Exception as e:
                logger.error(f"Failed to download from DB cache: {e}. Resetting completion state to force rebuild.")
                save_checkpoint({"date": str(datetime.now(IST).date())})
                raise RuntimeError("OUTPUT_PARQUET missing locally and in DB cache. Rebuild required.")
        
        logger.info("⏭️ Fundamentals already scored today. Loading final watchlist...")
        final_df = pd.read_parquet(OUTPUT_PARQUET)

    logger.info(f"✅ [COMPLETE] FINAL WATCHLIST SAVED: {len(final_df)} stocks")

    print("\n── Top 10 ──────────────────────────────────────\n")
    print(final_df.head(10).to_string(index=False))

    # =================================================================================
    # NOTIFICATIONS DISABLED (2026-06-17)
    # Email and Telegram notifications removed per user request.
    # Database deduplication (check_data_exists_for_today) prevents re-runs on restart.
    # =================================================================================
    logger.info("✅ Daily Builder completed successfully (notifications disabled)")
    
    # Clean up checkpoint on full success
    try:
        from database import save_system_state
        save_system_state("daily_builder_checkpoint", "")
        logger.info("✅ Build complete. Checkpoint removed from DB.")
    except Exception as e:
        logger.warning(f"Could not remove checkpoint from DB: {e}")

# =====================================================================================
# ALIAS
build_watchlist = main

if __name__ == "__main__":
    main()
