# =====================================================================================
# app/eod_scanner.py (SCHEDULER READY)
# EOD BREAKOUT SCANNER WITH CONSOLIDATED MAIL AUTOMATION
# =====================================================================================

import pandas as pd
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed, TimeoutError

from zoneinfo import ZoneInfo
from datetime import datetime

from technical_indicators import apply_indicators
from breakout_engine import detect_breakouts
from scoring_engine import calculate_score
from sector_rotation import get_sector_scores, SectorRotationResult
from surveillance import get_live_blacklist, force_refresh_blacklist
from macro_utils import get_nifty_20d_return, get_macro_regime
from database import (
    init_db, save_alert_if_new, upsert_fetch_error,
    upsert_scanner_health, insert_notification,
    get_recent_alerts_for_scanner, verify_alerts_saved_today
)
from delivery_data import fetch_delivery_data
from price_cache import fetch_watchlist_data
from sl_target_helper import compute_sl_and_target
from watchlist_cache import get_watchlist
import time
import database

from config import (
    EOD_CONFIG,
    EOD_ADVANCED_CONFIG,
    ALERT_COOLDOWN_MINUTES,
    ADX_MIN_THRESHOLD,
    MIN_STOCK_PRICE,
    SCORE_THRESHOLDS,
)

logger = logging.getLogger(__name__)

IST        = ZoneInfo("Asia/Kolkata")

MIN_SIGNALS             = EOD_CONFIG["MIN_SIGNALS"]
MIN_BODY_RATIO          = EOD_CONFIG["MIN_BODY_RATIO"]
MIN_CLOSE_POSITION      = EOD_CONFIG["MIN_CLOSE_POSITION"]
MAX_UPPER_WICK_RATIO    = EOD_CONFIG["MAX_UPPER_WICK"]
MIN_VOLUME_RATIO        = EOD_CONFIG["MIN_VOLUME_RATIO"]    
MIN_AVG_VOLUME_SHARES   = EOD_CONFIG["MIN_VOLUME_AVG"]      
MIN_RSI                 = EOD_CONFIG["MIN_RSI"]             
MAX_RSI                 = EOD_CONFIG["MAX_RSI"]                   

# MIN_STOCK_PRICE imported from config (₹100)
MAX_DISTANCE_FROM_52W_HIGH_PCT = EOD_ADVANCED_CONFIG["MAX_DISTANCE_FROM_52W_HIGH_PCT"]

from lock_utils import ProcessLock
_scan_lock = ProcessLock("eod_scanner")

def start(force: bool = False):
    if not _scan_lock.acquire(blocking=False):
        raise RuntimeError("Scanner is already actively running!")
    try:
        return _start_wrapper(force)
    finally:
        _scan_lock.release()

def _start_wrapper(force: bool = False):
    is_test_mode = True  # Safe default
    init_db()
    
    force_refresh_blacklist()
    
    nifty_ret_20d = get_nifty_20d_return()

    
    ist_now = datetime.now(IST)
    logger.info("\n" + "=" * 80)
    logger.info(f"🚀🚀🚀 [START] EOD SCANNER INIT | {ist_now.strftime('%Y-%m-%d %H:%M:%S')} 🚀🚀🚀")
    logger.info("=" * 80 + "\n")
    
    start_time = datetime.now(IST)

    # Check if we are outside the valid EOD window (18:30 - 23:59:59)
    now_time = ist_now.time()
    scan_start = datetime.strptime("18:30", "%H:%M").time()
    scan_end = datetime.strptime("23:59:59", "%H:%M:%S").time()
    
    if force:
        is_test_mode = False
    else:
        is_test_mode = getattr(database, "DONT_SAVE_ALERTS", False) or not (scan_start <= now_time <= scan_end)
    if is_test_mode:
        logger.info("🧪 [TEST MODE] Outside scheduled window (18:30-23:59). Alerts will NOT be saved to DB.")

    try:
        try:
            watchlist = get_watchlist()
            # ── DUAL MANDATE REMOVED ──
            # EOD Scanner now runs on the entire elite fundamental watchlist generated by the Daily Builder.
            logger.info(f"🛡️ EOD Scanner running on full fundamental watchlist: {len(watchlist)} stocks")
                
        except Exception as e:
            # [VERSION: EOD_PATCH_v1.0] [BUG FIX 1] Remove 5-min sleep inside the lock. Let the scheduler handle backoff.
            logger.exception("❌ Failed to load watchlist")
            if not is_test_mode:
                try:
                    from database import upsert_scanner_health
                    upsert_scanner_health(scanner_name="EOD", status="DOWN", error_msg=f"Watchlist load failed: {str(e)[:200]}")
                except Exception:
                    pass
            return 0

        if watchlist.empty:
            logger.info("🛡️ EOD Scanner | Universe is empty (no stocks passed Wealth Engine BUY signals). Exiting cleanly.")
            if not is_test_mode:
                try:
                    from database import insert_notification, upsert_scanner_health
                    insert_notification("admin", "🚀 EOD Scanner ran successfully. Found 0 new breakout alerts.", "Generated 0 alerts. The fundamental watchlist universe is currently empty.")
                    upsert_scanner_health("EOD", status="OK", last_success=datetime.now(IST).isoformat(), today_alerts=0, total_count=0)
                except Exception:
                    pass
            return 0

        # We do NOT purge here yet.
        # Purge only after upstream validation and fetch sufficiency checks succeed.
        # [VERSION: EOD_PATCH_v1.0] [BUG FIX 5] Compute today_str once here and reuse it throughout to avoid duplication
        today_str = ist_now.strftime("%Y-%m-%d")

        delivery_map: dict[str, float] = {}
        all_ticker_data = {}

        # [VERSION: EOD_PATCH_v1.1] [BUG FIX 7 REGRESSION FIX] Explicit shutdown(wait=False) to prevent 'with' block from hanging
        pool = ThreadPoolExecutor(max_workers=2)
        try:
            future_delivery = pool.submit(fetch_delivery_data, ist_now.date())
            # Keep "2y" for EOD - needs 2 years of volume data for delivery analysis
            # EOD has separate cache key (1d, 2y) but still benefits from TTL extensions
            future_prices   = pool.submit(fetch_watchlist_data, watchlist, "2y", "1d")
            
            try:
                # [VERSION: EOD_PATCH_v1.0] [BUG FIX 7] Add timeout to ThreadPoolExecutor to prevent hanging indefinitely
                for future in as_completed([future_delivery, future_prices], timeout=120):
                    if future is future_delivery:
                        delivery_map = future.result()
                    else:
                        all_ticker_data = future.result()
            except TimeoutError:
                logger.error("❌ Data fetch timed out after 120s (likely API hung)")
                pool.shutdown(wait=False)
                raise Exception("TIMEOUT: Fetch operation exceeded 120 seconds")
        finally:
            pool.shutdown(wait=True, timeout=5)

        # Rate-limit safety net
        # If we failed to fetch data for more than 50% of the watchlist, we must throw an error 
        # so that main.py catches it and retries later when rate limits clear.
        fetched_count = len(all_ticker_data) if all_ticker_data else 0
        if fetched_count < len(watchlist) * 0.70:
            logger.warning(f"⚠️ Data Provider returned data for only {fetched_count}/{len(watchlist)} symbols (likely rate-limited). Forcing retry...")
            if not is_test_mode:
                try:
                    upsert_scanner_health(scanner_name="EOD", status="DOWN", error_msg=f"STALE DATA/INCOMPLETE DATA ERROR: Fetched {fetched_count}/{len(watchlist)} symbols")
                except Exception:
                    pass
            raise Exception(f"STALE DATA/INCOMPLETE DATA ERROR: Only fetched {fetched_count}/{len(watchlist)} symbols (70% minimum required). Aborting to prevent stale data.")
        else:
            logger.info(f"✅ Successfully fetched {fetched_count}/{len(watchlist)} symbols for EOD scan")

        # today_str already computed above

        # ── IDEMPOTENT PARTITION OVERWRITE ──
        # EOD writes to `alerts` via save_alert_if_new(), so cleanup must target `alerts`.
        if not is_test_mode:
            try:
                from database import getconnection
                with getconnection() as conn:
                    with conn.cursor() as cur:
                        cur.execute(
                            "DELETE FROM alerts WHERE scanner = %s AND alert_date = %s",
                            ("EOD", today_str)
                        )
                        if cur.rowcount > 0:
                            logger.info(f"🧹 Cleaned up {cur.rowcount} previous EOD alerts for {today_str} to ensure idempotency.")
                    conn.commit()
            except Exception as e:
                logger.error(f"Failed to cleanup today's EOD alerts from alerts table: {e}")
                raise

        # IMPORTANT:
        # Fetch cooldown state AFTER deleting today's rows, so it reflects a clean state.
        cooldown_alerts = get_recent_alerts_for_scanner("EOD", ALERT_COOLDOWN_MINUTES["EOD"])

        # FIX: NSE bhavcopy for today may not be published until ~19:00–19:30 IST.
        # If today's file returned empty, fall back to the most recent available trading day.
        if not delivery_map:
            logger.warning("⚠️ Today's bhavcopy not yet available — falling back to previous trading day delivery data.")
            from delivery_data import fetch_previous_day_delivery
            delivery_map = fetch_previous_day_delivery()

        try:
            rotation_result = get_sector_scores()
        except Exception:
            rotation_result = SectorRotationResult({}, set(), set(), "", datetime.now(IST).date(), 0.0)

        total_alerts       = 0
        alerts_by_category = {}

        rejection_counts = {k: 0 for k in [
            "no_data", "missing_col", "insufficient_bars", "indicator_fail", "weak_signals",
            "weak_body", "bearish_candle", "weak_close_pos", "upper_wick", "low_volume",
            "low_avg_volume", "penny_stock", "rsi_range", "below_ema20",
            "below_sma50", "weak_adx", "far_from_52w_high",
            "gap_day", "extended_breakout", "gap_extended", "low_score", "duplicate", "stale_data",
            "prior_red_candles", "obv_divergence", 
            "no_structural_breakout", "no_atr_expansion", "base_too_wide",
            "missing_atr", "zero_avg_volume", "zero_candle_range"
        ]}
        
        market_regime = get_macro_regime(nifty_ret_20d)
        logger.info(f"📊 Market Regime Classifier: {market_regime}")

        if market_regime == "BEAR":
            logger.info("🛑 BEAR regime detected — skipping EOD breakout scan entirely.")
            if not is_test_mode:
                try:
                    upsert_scanner_health(
                        scanner_name="EOD",
                        status="OK",
                        last_success=datetime.now(IST).isoformat(),
                        today_alerts=0,
                        total_count=len(watchlist),
                        error_msg="Skipped: BEAR regime"
                    )
                except Exception:
                    logger.exception("❌ Failed to update scanner health for EOD early return")
            return 0


        # Compute threshold outside loop
        BASE_SCORE_THRESHOLD = SCORE_THRESHOLDS.get("1d", 82)
        # Single threshold for all regimes (BEAR already skipped above)
        # In strong markets, good setups flow. In neutral, only best setups pass.
        global_min_score = BASE_SCORE_THRESHOLD
        
        logger.info(f"📊 Score threshold for {market_regime} regime: {global_min_score}")

        for idx, (_, row) in enumerate(watchlist.iterrows(), start=1):
            symbol = "UNKNOWN"
            try:
                symbol   = row["Stock"]
                category = row["Category"]
                sector   = row.get("Sector", None)

                if symbol in get_live_blacklist():
                    continue

                if symbol not in all_ticker_data:
                    rejection_counts["no_data"] += 1
                    continue

                ticker = all_ticker_data[symbol].copy()

                if ticker.empty:
                    rejection_counts["no_data"] += 1
                    continue

                # If provider returned stale data (used as fallback during rate limits), skip EOD buy generation
                if getattr(ticker, 'attrs', {}).get('is_stale'):
                    rejection_counts["stale_data"] += 1
                    continue

                if isinstance(ticker.columns, pd.MultiIndex):
                    ticker.columns = ticker.columns.get_level_values(0)

                ticker = ticker.loc[:, ~ticker.columns.duplicated()]

                required_cols = ["Open", "High", "Low", "Close", "Volume"]
                missing_col   = False

                for col_name in required_cols:
                    if col_name not in ticker.columns:
                        missing_col = True
                        break
                    if isinstance(ticker[col_name], pd.DataFrame):
                        ticker[col_name] = ticker[col_name].iloc[:, 0]
                    ticker[col_name] = pd.Series(ticker[col_name]).astype(float)

                if missing_col:
                    rejection_counts["missing_col"] += 1
                    continue

                ticker = ticker.dropna(subset=["Open", "High", "Low", "Close", "Volume"])

                if ticker.empty:
                    rejection_counts["no_data"] += 1
                    continue

                if len(ticker) < 200:
                    rejection_counts["insufficient_bars"] += 1
                    continue

                ticker = apply_indicators(ticker, timeframe="1d")

                if ticker is None or ticker.empty:
                    rejection_counts["indicator_fail"] += 1
                    continue

                signals = detect_breakouts(ticker, timeframe="1d")

                if len(signals) < MIN_SIGNALS:
                    rejection_counts["weak_signals"] += 1
                    continue

                latest = ticker.iloc[-1]

                if "RSI" not in ticker.columns or pd.isna(latest["RSI"]):
                    continue

                # [VERSION: EOD_PATCH_v1.1] [BUG FIX 8 REGRESSION FIX] Proper fallback to DatetimeIndex when Date/Datetime column is missing
                _stale_col = next((c for c in ["Date", "Datetime"] if c in ticker.columns), None)
                if _stale_col:
                    try:
                        _last_ts = pd.to_datetime(latest[_stale_col])
                        if _last_ts.tzinfo is not None:
                            _last_ts = _last_ts.tz_convert("Asia/Kolkata")
                        if _last_ts.date() != ist_now.date():
                            rejection_counts["stale_data"] += 1
                            continue
                    except Exception as e:
                        logger.debug(f"⏭️ {symbol} stale-data check failed: {e}")
                        rejection_counts["stale_data"] += 1
                        continue
                elif isinstance(ticker.index, pd.DatetimeIndex):
                    try:
                        _last_ts = pd.Timestamp(ticker.index[-1])
                        if _last_ts.tzinfo is not None:
                            _last_ts = _last_ts.tz_convert("Asia/Kolkata")
                        else:
                            _last_ts = _last_ts.tz_localize("UTC").tz_convert("Asia/Kolkata")
                        if _last_ts.date() != ist_now.date():
                            rejection_counts["stale_data"] += 1
                            continue
                    except Exception as e:
                        logger.debug(f"⏭️ {symbol} stale-data check failed (index): {e}")
                        rejection_counts["stale_data"] += 1
                        continue
                else:
                    logger.debug(f"⏭️ {symbol} no timestamp available (neither column nor DatetimeIndex)")
                    rejection_counts["stale_data"] += 1
                    continue

                latest_volume = float(latest["Volume"])
                avg_volume    = float(ticker["Volume"].iloc[-21:-1].mean())

                if avg_volume <= 0:
                    # [VERSION: EOD_PATCH_v1.0] [BUG FIX 3] Rejection counters updated for zero volume and candle range
                    rejection_counts["zero_avg_volume"] += 1
                    continue

                volume_ratio = latest_volume / avg_volume

                candle_high  = float(latest["High"])
                candle_low   = float(latest["Low"])
                candle_open  = float(latest["Open"])
                candle_close = float(latest["Close"])
                candle_range = candle_high - candle_low
                candle_body  = abs(candle_close - candle_open)
                upper_wick   = candle_high - candle_close

                if candle_range <= 0:
                    rejection_counts["zero_candle_range"] += 1
                    continue

                body_ratio     = candle_body / candle_range
                close_position = (candle_close - candle_low) / candle_range
                wick_ratio     = upper_wick / candle_range
                rsi_val        = float(latest["RSI"])

                if body_ratio < MIN_BODY_RATIO:
                    rejection_counts["weak_body"] += 1
                    continue
                if candle_close <= candle_open:
                    rejection_counts["bearish_candle"] += 1
                    continue
                if close_position < MIN_CLOSE_POSITION:
                    rejection_counts["weak_close_pos"] += 1
                    continue
                if wick_ratio > MAX_UPPER_WICK_RATIO:
                    rejection_counts["upper_wick"] += 1
                    continue
                if volume_ratio < MIN_VOLUME_RATIO:
                    rejection_counts["low_volume"] += 1
                    continue
                if avg_volume < MIN_AVG_VOLUME_SHARES:
                    rejection_counts["low_avg_volume"] += 1
                    continue
                if candle_close < MIN_STOCK_PRICE:
                    rejection_counts["penny_stock"] += 1
                    continue
                if not (MIN_RSI <= rsi_val <= MAX_RSI):
                    rejection_counts["rsi_range"] += 1
                    continue

                # ── v6: STRUCTURAL BREAKOUT FILTERS ─────────────────────────────
                # [VERSION: EOD_PATCH_v1.0] [BUG FIX 2] Added explicit outer else rejection to avoid silent bypass of structural filters
                if "PRIOR_20D_HIGH" not in ticker.columns or pd.isna(latest.get("PRIOR_20D_HIGH")):
                    rejection_counts["missing_atr"] += 1
                    continue

                prior_high = float(latest["PRIOR_20D_HIGH"])
                if prior_high <= 0:
                    rejection_counts["no_structural_breakout"] += 1
                    continue

                if candle_close <= prior_high:
                    rejection_counts["no_structural_breakout"] += 1
                    continue

                # Not Extended
                if "ATR20" not in ticker.columns or pd.isna(latest.get("ATR20")):
                    rejection_counts["missing_atr"] += 1
                    continue

                atr20 = float(latest["ATR20"])
                if atr20 <= 0:
                    rejection_counts["missing_atr"] += 1
                    continue

                if (candle_close - prior_high) > EOD_ADVANCED_CONFIG.get("MAX_EXTENDED_BREAKOUT_ATR_MULT", 1.5) * atr20:
                    rejection_counts["extended_breakout"] += 1
                    continue
                
                # ATR Expansion
                if candle_range / atr20 < EOD_ADVANCED_CONFIG.get("MIN_ATR_EXPANSION_RATIO", 1.2):
                    rejection_counts["no_atr_expansion"] += 1
                    continue

                if "BB_WIDTH_PCTILE" in ticker.columns and not pd.isna(latest.get("BB_WIDTH_PCTILE")):
                    bb_width_pctile = float(latest["BB_WIDTH_PCTILE"])
                    if bb_width_pctile > EOD_ADVANCED_CONFIG.get("MAX_BB_WIDTH_PCTILE", 0.80):
                        rejection_counts["base_too_wide"] += 1
                        continue

                if "EMA20" in ticker.columns and not pd.isna(latest.get("EMA20")):
                    if candle_close < float(latest["EMA20"]):
                        rejection_counts["below_ema20"] += 1
                        continue

                if "SMA50" in ticker.columns and not pd.isna(latest.get("SMA50")):
                    if candle_close < float(latest["SMA50"]):
                        rejection_counts["below_sma50"] += 1
                        continue

                # Golden Cross is no longer mandatory, shifted to scoring engine

                if "ADX" in ticker.columns and not pd.isna(latest.get("ADX")):
                    if float(latest["ADX"]) < ADX_MIN_THRESHOLD:
                        rejection_counts["weak_adx"] += 1
                        continue

                # MACD is no longer mandatory, shifted to scoring engine

                if "HIGH_52W" in ticker.columns and not pd.isna(latest.get("HIGH_52W")):
                    high_52w = float(latest["HIGH_52W"])
                    if high_52w > 0:
                        pct_from_high = (high_52w - candle_close) / high_52w * 100
                        if pct_from_high > MAX_DISTANCE_FROM_52W_HIGH_PCT:
                            rejection_counts["far_from_52w_high"] += 1
                            continue

                if len(ticker) >= 2:
                    prev_close = float(ticker["Close"].iloc[-2])
                    if prev_close > 0:
                        single_move_pct = abs(candle_close - prev_close) / prev_close * 100
                        max_single_day_move_pct = EOD_ADVANCED_CONFIG.get("MAX_SINGLE_DAY_MOVE_PCT", 15.0)
                        if single_move_pct > max_single_day_move_pct:
                            rejection_counts["gap_day"] += 1
                            continue

                gap_lookback_bars = EOD_ADVANCED_CONFIG.get("GAP_LOOKBACK_BARS", 10)
                max_gap_pct = EOD_ADVANCED_CONFIG.get("MAX_GAP_FROM_PRIOR_HIGH_PCT", 3.0)
                if len(ticker) >= gap_lookback_bars + 1:
                    gap_reference_high = float(ticker["High"].iloc[-(gap_lookback_bars + 1):-1].max())
                    if gap_reference_high > 0:
                        gap_pct = (candle_open - gap_reference_high) / gap_reference_high * 100
                        if gap_pct > max_gap_pct:
                            rejection_counts["gap_extended"] += 1
                            continue

                delivery_pct = delivery_map.get(symbol, None)

                # ── v5: PREVIOUS CANDLE CONTEXT FILTER ─────────────────────────────
                lookback = EOD_ADVANCED_CONFIG.get("PRE_BREAKOUT_LOOKBACK_BARS", 5)
                max_red = EOD_ADVANCED_CONFIG.get("MAX_PRE_BREAKOUT_RED_CANDLES", 2)
                tight_base_threshold = EOD_ADVANCED_CONFIG.get("TIGHT_BASE_BB_WIDTH_PCTILE", 0.35)
                
                if len(ticker) >= (lookback + 1):
                    red_count = 0
                    for _ri in range(-(lookback + 1), -1):
                        if float(ticker["Close"].iloc[_ri]) < float(ticker["Open"].iloc[_ri]):
                            red_count += 1
                    
                    if red_count > max_red:
                        # Too many red candles. Reject unless it's a very tight base (volatility compression)
                        is_tight_base = False
                        if "BB_WIDTH_PCTILE" in ticker.columns and not pd.isna(latest.get("BB_WIDTH_PCTILE")):
                            if float(latest["BB_WIDTH_PCTILE"]) <= tight_base_threshold:
                                is_tight_base = True
                                
                        if not is_tight_base:
                            rejection_counts["prior_red_candles"] += 1
                            continue

                # ── v6: OBV STRUCTURE FILTER ────────────────────────────────────
                if "OBV_SLOPE" in ticker.columns and not pd.isna(latest.get("OBV_SLOPE")):
                    if float(latest["OBV_SLOPE"]) <= EOD_ADVANCED_CONFIG.get("MIN_OBV_SLOPE", 0.0):
                        rejection_counts["obv_divergence"] += 1
                        continue

                atr_val_eod = (
                    float(latest["ATR"])
                    if "ATR" in ticker.columns and not pd.isna(latest.get("ATR"))
                    else None
                )


                score, model_version, bayesian_weights = calculate_score(
                    category=category,
                    breakout_count=len(signals),
                    rsi=rsi_val,
                    volume_ratio=volume_ratio,
                    breakout_signals=signals,
                    ticker=ticker,
                    latest=latest,
                    symbol=symbol,
                    timeframe="1d",
                    atr_val=atr_val_eod,
                    delivery_pct=delivery_pct,
                    nifty_ret=nifty_ret_20d,
                    regime=market_regime
                )

                if score > 0:
                    try:
                        safe_sector  = "Unknown" if (sector is None or (isinstance(sector, float) and pd.isna(sector))) else str(sector).strip()
                        sector_bonus = rotation_result.score_bonus_for(safe_sector)
                        score = max(0, min(score + sector_bonus, 100))
                    except Exception:
                        pass

                # ── REGIME-AWARE THRESHOLDS ──────────────────────────────────────
                if score < global_min_score:
                    rejection_counts["low_score"] += 1
                    continue

                signal_str = ", ".join(signals.keys() if isinstance(signals, dict) else signals)
                today_str  = ist_now.strftime("%Y-%m-%d")
                dedup_key  = f"{category}|{signal_str}|{today_str}|EOD"

                if (symbol, dedup_key) in cooldown_alerts:
                    rejection_counts["duplicate"] += 1
                    continue

                # ── Dynamic S/R and Indicator-based SL + Target (EOD mode) ───────
                sl_result = compute_sl_and_target(
                    entry_price=candle_close,
                    atr=atr_val_eod,
                    candle_range=candle_range,
                    mode="EOD",
                    adx=latest.get("ADX"),
                    rsi=rsi_val,
                    macd_hist=latest.get("MACD_HIST"),
                    atr_pct=latest.get("ATR_PCT"),
                    swing_low=latest.get("SWING_LOW"),
                    swing_high=latest.get("SWING_HIGH"),
                    bb_upper=latest.get("BB_UPPER"),
                    bb_lower=latest.get("BB_LOWER"),
                    bb_mid=latest.get("BB_MID"),
                    s1=latest.get("S1"),
                    s2=latest.get("S2"),
                    r1=latest.get("R1"),
                    r2=latest.get("R2"),
                    swing_low_raw=latest.get("SWING_LOW_RAW"),
                    swing_high_raw=latest.get("SWING_HIGH_RAW"),
                    candle_low=candle_low,
                    vwap=latest.get("VWAP"),
                )
                suggested_stop = sl_result["stop_loss"]
                target_price = sl_result["target_1"]

                above_ema20  = bool(candle_close >= float(latest["EMA20"])) if "EMA20" in ticker.columns and not pd.isna(latest.get("EMA20")) else None
                above_sma50  = bool(candle_close >= float(latest["SMA50"])) if "SMA50" in ticker.columns and not pd.isna(latest.get("SMA50")) else None
                # [VERSION: EOD_PATCH_v1.0] [BUG FIX 6] Renamed golden_cross to above_golden_cross to accurately reflect it's a state check
                above_golden_cross = bool(float(latest["SMA50"]) >= float(latest["SMA200"])) if ("SMA50" in ticker.columns and "SMA200" in ticker.columns and not pd.isna(latest.get("SMA50")) and not pd.isna(latest.get("SMA200"))) else None

                context = {
                    "technicals": {
                        "above_ema20":      above_ema20,
                        "above_sma50":      above_sma50,
                        "above_golden_cross":     above_golden_cross,
                        "body_ratio":       round(body_ratio * 100, 2),
                        "delivery_pct":     round(delivery_pct, 1) if delivery_pct is not None else None,
                        "rsi":              round(rsi_val, 1),
                        "volume_ratio":     round(volume_ratio, 2),
                        "breakout_level":   round(float(latest.get("PRIOR_20D_HIGH")), 2) if "PRIOR_20D_HIGH" in latest else None,
                        "atr20":            round(float(latest.get("ATR20")), 2) if "ATR20" in latest else None,
                        "regime":           market_regime,
                        "score":            score
                    },
                    "session": {
                        "open":             round(candle_open, 2),
                        "day_high":         round(candle_high, 2),
                        "day_low":          round(candle_low, 2)
                    },
                    "fundamentals": {
                        "peg":              row.get("PEG Ratio"),
                        "yoy_rev":          row.get("YOY Revenue %"),
                        "yoy_profit":       row.get("YOY Profit %"),
                        "roe":              row.get("ROE %")
                    },
                    "execution": {
                        "sl_method":        sl_result.get("sl_method"),
                        "t_method":         sl_result.get("t_method"),
                        "trail_note":       sl_result.get("trail_note")
                    }
                }

                if not is_test_mode:
                    saved, cap_alloc, shares = save_alert_if_new(
                        symbol,
                        dedup_key,
                        ist_now.strftime("%Y-%m-%d %H:%M:%S+05:30"),
                        scanner="EOD",
                        category=category,
                        entry_price=round(candle_close, 2),
                        signals=signal_str,
                        score=score,
                        rsi=round(rsi_val, 1),
                        volume_ratio=round(volume_ratio, 2),
                        stop_loss=suggested_stop,
                        target_price=target_price,
                        context=context,
                        model_version=model_version,
                        bayesian_regime=market_regime,
                        bayesian_weights=bayesian_weights
                    )
                else:
                    saved, cap_alloc, shares = True, 0.0, 0

                if not saved:
                    rejection_counts["duplicate"] += 1
                    continue

                alerts_by_category.setdefault(category, []).append({
                    "symbol":           symbol,
                    "category":         category,
                    "breakout_signals": list(signals.keys()) if isinstance(signals, dict) else signals,
                    "price":            round(candle_close, 2),
                    "open":             round(candle_open, 2),
                    "day_high":         round(candle_high, 2),
                    "day_low":          round(candle_low, 2),
                    "rsi":              round(rsi_val, 1),
                    "volume_ratio":     round(volume_ratio, 2),
                    "body_ratio":       round(body_ratio * 100),
                    "close_position":   round(close_position * 100),
                    "score":            score,
                    "above_ema20":      above_ema20,
                    "above_sma50":      above_sma50,
                    "above_golden_cross":     above_golden_cross,
                    "atr_stop":         suggested_stop,
                    "target_price":     target_price,
                    "target_2":         sl_result.get("target_2"),
                    "target_3":         sl_result.get("target_3"),
                    "sl_method":        sl_result.get("sl_method"),
                    "t_method":         sl_result.get("t_method"),
                    "rr_ratio":         sl_result.get("rr_ratio"),
                    "trail_note":       sl_result.get("trail_note"),
                    "delivery_pct":     round(delivery_pct, 1) if delivery_pct is not None else None,
                    "peg":              row.get("PEG Ratio"),
                    "yoy_rev":          row.get("YOY Revenue %"),
                    "yoy_profit":       row.get("YOY Profit %"),
                    "roe":              row.get("ROE %"),
                    "capital_allocated": cap_alloc,
                    "shares_bought":     shares
                })
                total_alerts += 1

            # [VERSION: EOD_PATCH_v1.0] [BUG FIX 4] Catch general Exceptions rather than specific errors to prevent ZeroDivisionError/AttributeError from crashing the entire scan loop
            except Exception as e:
                error_type = type(e).__name__
                logger.warning(f"⚠️ Exception ({error_type}) processing {symbol}: {str(e)[:100]}")
                rejection_counts["indicator_fail"] = rejection_counts.get("indicator_fail", 0) + 1
                if not is_test_mode:
                    try:
                        upsert_fetch_error('yfinance', 'EOD', symbol, '1d', f'processing_error_{error_type}', str(e)[:500])
                    except Exception:
                        logger.exception(f'Failed to upsert fetch error for {symbol}')
                continue

        # ── VERIFICATION & STATUS ────────────────────────────────────────────────────
        # Removed Telegram notifications (2026-06-17)

        fired = {k: v for k, v in rejection_counts.items() if v > 0}
        if fired:
            logger.info("   Rejections: " + " | ".join(f"{k}={v}" for k, v in fired.items()))

        # ✅ CRITICAL: Verify alerts were actually saved to database (2026-06-17)
        if total_alerts > 0 and not is_test_mode:
            if not verify_alerts_saved_today("EOD", total_alerts):
                logger.critical(f"🚨 CRITICAL ERROR: EOD generated {total_alerts} alerts but save failed!")
                upsert_scanner_health(
                    scanner_name="EOD",
                    status="DOWN",
                    error_msg=f"CRITICAL: {total_alerts} alerts failed to save to database"
                )
                raise RuntimeError("Alert save verification failed - database connectivity issue")

        status = "OK"
        error_msg = None
        
        stale_pct = rejection_counts["stale_data"] / len(watchlist) if len(watchlist) > 0 else 0
        if stale_pct > 0.1:
            status = "DEGRADED"
            error_msg = f"Stale Data: {rejection_counts['stale_data']}/{len(watchlist)} symbols"
            
        if len(all_ticker_data) < len(watchlist):
            status = "DEGRADED"
            error_msg = f"Partial Fetch: {len(all_ticker_data)}/{len(watchlist)} symbols"

        if not is_test_mode:
            try:
                upsert_scanner_health(
                    scanner_name="EOD",
                    status=status,
                    last_success=datetime.now(IST).isoformat(),
                    today_alerts=total_alerts,
                    total_count=len(watchlist),
                    error_msg=error_msg
                )
            except Exception:
                logger.exception("❌ Failed to update scanner health for EOD")
            if status == "OK":
                try:
                    insert_notification("admin", f"🚀 EOD Scanner ran successfully. Found {total_alerts} new breakout alerts.", f"Generated {total_alerts} alerts from {len(watchlist)} scanned stocks.")
                except Exception:
                    pass

        elapsed_time = (datetime.now(IST) - start_time).total_seconds()
        logger.info("\n" + "=" * 80)
        logger.info(f"🛑🛑🛑 [COMPLETE] EOD SCANNER DONE | {elapsed_time:.2f}s | Alerts={total_alerts} | Status={status} 🛑🛑🛑")
        logger.info("=" * 80 + "\n")
        return total_alerts

    except Exception as e:
        logger.exception("❌ CRITICAL EOD SCAN ERROR")
        if not is_test_mode:
            try:
                upsert_scanner_health(scanner_name="EOD", status="DOWN", error_msg=str(e))
            except Exception:
                pass
        raise  # re-raise so caller can send Telegram crash alert
