# =====================================================================================
# app/eod_alert_builder.py
# EOD BREAKOUT SCANNER — Rich Alert Report Builder
#
# Responsibility:
#   Assembles a structured, human-readable terminal report for every alert
#   generated by the EOD scanner.  The report mirrors the richness of the
#   Multi-TF alert_builder card so that EOD output is equally diagnostic.
#
# Consumed by:
#   eod_scanner.py  → called once per scan cycle after approved_candidates
#   are persisted, using the fully-populated `alerts_by_category` dict.
#
# Input dict keys (per alert, from alerts_by_category values):
#   symbol, category, breakout_signals, price, open, day_high, day_low,
#   rsi, volume_ratio, body_ratio, close_position, score, above_ema20,
#   above_sma50, above_golden_cross, atr_stop, target_price, target_2,
#   target_3, sl_method, t_method, rr_ratio, delivery_pct,
#   peg, yoy_rev, yoy_profit, roe, capital_allocated, shares_bought
# =====================================================================================

from __future__ import annotations

import logging
from datetime import datetime
from typing import Dict, List, Any, Optional

logger = logging.getLogger("eod_alert_builder")

# ── Score tier labels ─────────────────────────────────────────────────────────
def _score_tier(score: int) -> str:
    if score >= 90: return "🔥 EXCEPTIONAL"
    if score >= 80: return "🚀 EXPLOSIVE"
    if score >= 70: return "🟢 SUPER"
    if score >= 60: return "🟡 GOOD"
    return "⚪ WATCH"


# ── RSI label ─────────────────────────────────────────────────────────────────
def _rsi_label(rsi: float) -> str:
    if rsi >= 75:  return f"{rsi:.1f}  ⚠️  (Overbought – caution)"
    if rsi >= 60:  return f"{rsi:.1f}  🟢  (Bullish momentum)"
    if rsi >= 45:  return f"{rsi:.1f}  🟡  (Neutral)"
    return         f"{rsi:.1f}  🔵  (Building / early)"


# ── Volume label ──────────────────────────────────────────────────────────────
def _vol_label(vr: float) -> str:
    if vr >= 3.0: return f"{vr:.2f}×  🚀🚀  (Exceptional)"
    if vr >= 2.0: return f"{vr:.2f}×  🚀   (Very strong)"
    if vr >= 1.5: return f"{vr:.2f}×  🔥   (Strong)"
    if vr >= 1.2: return f"{vr:.2f}×  🟢   (Confirmed)"
    return        f"{vr:.2f}×  🟡   (Moderate)"


# ── RR label ──────────────────────────────────────────────────────────────────
def _rr_label(rr: Optional[float]) -> str:
    if rr is None: return "—"
    if rr >= 3.0: return f"{rr:.1f}:1  🔥  (Outstanding)"
    if rr >= 2.0: return f"{rr:.1f}:1  🟢  (Excellent)"
    if rr >= 1.5: return f"{rr:.1f}:1  ✅  (Good)"
    return        f"{rr:.1f}:1  ⚠️  (Marginal)"


# ── Currency formatter ────────────────────────────────────────────────────────
def _rs(value: Any, decimals: int = 2) -> str:
    """Format a value as Indian Rupee with comma grouping."""
    try:
        v = float(value)
        # Build locale-style Indian number with commas
        s = f"{v:,.{decimals}f}"
        return f"₹{s}"
    except (TypeError, ValueError):
        return "₹—"


# ── Close-position description ────────────────────────────────────────────────
def _close_pos_desc(pct: int) -> str:
    """pct is 0-100 (percentage of day range)."""
    if pct >= 85: return "top 15% of range  🔥"
    if pct >= 70: return "top 30% of range  🟢"
    if pct >= 50: return "upper half  🟡"
    return "lower half  ⚠️"


# ── Body ratio description ────────────────────────────────────────────────────
def _body_desc(pct: int) -> str:
    if pct >= 70: return "dominant body  🟢"
    if pct >= 50: return "solid body  🟡"
    return "small body  ⚠️"


# ── Optional fundamental line ─────────────────────────────────────────────────
def _opt_pct(label: str, value: Any, positive_threshold: float = 0.0) -> Optional[str]:
    try:
        v = float(value)
        sign = "+" if v > 0 else ""
        ok = "🟢" if v > positive_threshold else "🔴"
        return f"  {label:<20} {sign}{v:.1f}%  {ok}"
    except (TypeError, ValueError):
        return None


def _opt_val(label: str, value: Any, decimals: int = 1) -> Optional[str]:
    try:
        v = float(value)
        return f"  {label:<20} {v:.{decimals}f}"
    except (TypeError, ValueError):
        return None


# ── Build single alert card ───────────────────────────────────────────────────
def _build_alert_card(rank: int, total: int, alert: Dict[str, Any]) -> str:
    """
    Builds one structured terminal card for a single EOD alert.

    Args:
        rank   : 1-based alert rank (sorted by score desc)
        total  : total number of alerts in this cycle
        alert  : dict from alerts_by_category

    Returns:
        Formatted multi-line string ready for logger.info()
    """
    sym         = alert.get("symbol", "UNKNOWN")
    category    = alert.get("category", "—")
    score       = int(alert.get("score") or 0)
    price       = alert.get("price") or alert.get("entry_price") or 0.0
    o           = alert.get("open")      or 0.0
    h           = alert.get("day_high")  or 0.0
    l           = alert.get("day_low")   or 0.0
    rsi         = float(alert.get("rsi") or 0.0)
    vr          = float(alert.get("volume_ratio") or 0.0)
    body_pct    = int(alert.get("body_ratio") or 0)
    close_pct   = int(alert.get("close_position") or 0)
    above_ema   = bool(alert.get("above_ema20"))
    above_sma   = bool(alert.get("above_sma50"))
    golden      = bool(alert.get("above_golden_cross"))
    atr_stop    = alert.get("atr_stop")
    t1          = alert.get("target_price")
    t2          = alert.get("target_2")
    t3          = alert.get("target_3")
    sl_method   = alert.get("sl_method") or "—"
    t_method    = alert.get("t_method")  or "—"
    rr          = alert.get("rr_ratio")
    delivery    = alert.get("delivery_pct")
    peg         = alert.get("peg")
    yoy_rev     = alert.get("yoy_rev")
    yoy_profit  = alert.get("yoy_profit")
    roe         = alert.get("roe")
    cap_alloc   = alert.get("capital_allocated") or 0.0
    shares      = alert.get("shares_bought") or 0
    signals     = alert.get("breakout_signals") or []
    tier        = _score_tier(score)

    W = 66  # card width

    lines: List[str] = [
        "═" * W,
        f"  [{rank}/{total}]  {sym}  │  {category}",
        "═" * W,
        "",
        f"  🏆 QUALITY SCORE : {score}/100   {tier}",
        "",
    ]

    # ── Price Action ──────────────────────────────────────────────────────────
    lines += [
        "  ━━━ PRICE ACTION " + "━" * (W - 19),
        f"  {'OHLC':<20} {_rs(o)} / {_rs(h)} / {_rs(l)} / {_rs(price)}",
        f"  {'Body Ratio':<20} {body_pct}%  {_body_desc(body_pct)}",
        f"  {'Close Position':<20} {close_pct}%  {_close_pos_desc(close_pct)}",
        f"  {'RSI (14)':<20} {_rsi_label(rsi)}",
        f"  {'Volume Ratio':<20} {_vol_label(vr)}",
    ]
    if delivery is not None:
        try:
            dv = float(delivery)
            dv_flag = "🟢" if dv >= 40.0 else ("🟡" if dv >= 25.0 else "🔴")
            lines.append(f"  {'Delivery %':<20} {dv:.1f}%  {dv_flag}")
        except (TypeError, ValueError):
            pass
    lines.append("")

    # ── Structure & Signal ────────────────────────────────────────────────────
    lines += [
        "  ━━━ STRUCTURE & SIGNAL " + "━" * (W - 24),
    ]
    if signals:
        for sig in signals:
            if sig:
                lines.append(f"  {'Signal':<20} {str(sig)}")
    lines += [
        f"  {'Above EMA20':<20} {'✅' if above_ema else '❌'}",
        f"  {'Above SMA50':<20} {'✅' if above_sma else '❌'}",
        f"  {'Golden Cross':<20} {'✅' if golden else '—'}",
        "",
    ]

    # ── Trade Plan ────────────────────────────────────────────────────────────
    lines += [
        "  ━━━ TRADE PLAN " + "━" * (W - 16),
        f"  {'Entry':<20} {_rs(price)}",
        f"  {'Stop Loss':<20} {_rs(atr_stop)}  [{sl_method}]",
    ]
    if t1:
        lines.append(f"  {'T1 (Target)':<20} {_rs(t1)}  [{t_method}]")
    if t2:
        lines.append(f"  {'T2':<20} {_rs(t2)}")
    if t3:
        lines.append(f"  {'T3':<20} {_rs(t3)}")
    lines.append(f"  {'R:R Ratio':<20} {_rr_label(rr)}")
    lines.append("")

    # ── Fundamentals (only if any data present) ───────────────────────────────
    fund_lines: List[str] = []
    p_roe = _opt_val("ROE %", roe)
    if p_roe: fund_lines.append(p_roe + "  " + ("🟢" if (roe or 0) >= 15 else "🔴"))
    p_rev = _opt_pct("YOY Revenue %", yoy_rev)
    if p_rev: fund_lines.append(p_rev)
    p_profit = _opt_pct("YOY Profit %", yoy_profit)
    if p_profit: fund_lines.append(p_profit)
    p_peg = _opt_val("PEG Ratio", peg)
    if p_peg: fund_lines.append(p_peg)

    if fund_lines:
        lines += ["  ━━━ FUNDAMENTALS " + "━" * (W - 19)] + fund_lines + [""]

    # ── Capital Allocation ────────────────────────────────────────────────────
    if cap_alloc and float(cap_alloc) > 0:
        lines += [
            "  ━━━ CAPITAL ALLOCATION " + "━" * (W - 24),
            f"  {'Allocated':<20} {_rs(cap_alloc, 0)}",
            f"  {'Shares':<20} {int(shares):,}",
            "",
        ]

    return "\n".join(lines)


# ── Summary table ─────────────────────────────────────────────────────────────
def _build_summary_table(all_alerts: List[Dict[str, Any]]) -> str:
    """Builds a compact summary table of all alerts ranked by score."""
    W = 106
    hdr = (
        f"  {'#':<3} {'Symbol':<14} {'Score':>5}  {'Entry':>10}  "
        f"{'Stop':>10}  {'T1':>10}  {'RR':>5}  {'Vol×':>6}  {'RSI':>5}  Category"
    )
    sep = "  " + "─" * (W - 2)

    lines = [
        "═" * W,
        "  📋  EOD ALERT SUMMARY TABLE",
        "═" * W,
        hdr,
        sep,
    ]
    for i, a in enumerate(all_alerts, start=1):
        sym   = (a.get("symbol") or "—")[:13]
        score = int(a.get("score") or 0)
        entry = a.get("price") or a.get("entry_price") or 0.0
        stop  = a.get("atr_stop") or 0.0
        t1    = a.get("target_price") or 0.0
        rr    = a.get("rr_ratio") or 0.0
        vr    = float(a.get("volume_ratio") or 0.0)
        rsi   = float(a.get("rsi") or 0.0)
        cat   = (a.get("category") or "—")[:20]
        tier_char = (
            "🔥" if score >= 90 else
            "🚀" if score >= 80 else
            "🟢" if score >= 70 else
            "🟡"
        )
        try: rr_str = f"{float(rr):.1f}"
        except Exception: rr_str = "—"
        lines.append(
            f"  {i:<3} {sym:<14} {tier_char}{score:>3}   "
            f"₹{float(entry):>9,.2f}  ₹{float(stop):>9,.2f}  "
            f"₹{float(t1):>9,.2f}  {rr_str:>5}  {vr:>5.2f}  {rsi:>5.1f}  {cat}"
        )
    lines += [sep, ""]
    return "\n".join(lines)


# ── Public entry point ────────────────────────────────────────────────────────
def build_eod_scan_report(
    alerts_by_category: Dict[str, List[Dict[str, Any]]],
    market_regime: str,
    scan_ts: Optional[datetime] = None,
) -> str:
    """
    Builds the complete EOD scan report as a single multi-line string suitable
    for logger.info() output.

    Args:
        alerts_by_category : dict mapping category → list of alert dicts
                             (populated by eod_scanner.py)
        market_regime      : regime string e.g. "BULL", "BEAR", "NEUTRAL"
        scan_ts            : datetime of the scan (IST); defaults to now()

    Returns:
        Formatted report string.  Returns a brief notice if no alerts.
    """
    if not alerts_by_category:
        return (
            "\n╔══════════════════════════════════════════════════╗\n"
            "║    EOD SCAN REPORT  —  0 alerts generated         ║\n"
            "╚══════════════════════════════════════════════════╝\n"
        )

    # Flatten all alerts across categories, preserve score-sorted order
    all_alerts: List[Dict[str, Any]] = []
    for cat_alerts in alerts_by_category.values():
        all_alerts.extend(cat_alerts)
    all_alerts.sort(key=lambda a: int(a.get("score") or 0), reverse=True)

    total = len(all_alerts)

    if scan_ts is None:
        scan_ts = datetime.now()

    ts_str   = scan_ts.strftime("%d-%b-%Y  %H:%M IST")
    regime_emoji = {
        "BULL": "🐂", "BEAR": "🐻", "NEUTRAL": "➖", "SEVERE_BEAR": "🔴", "STRONG_BULL": "🚀"
    }.get(market_regime, "")

    W = 66
    header_lines = [
        "\n" + "═" * W,
        f"  📊  EOD BREAKOUT SCANNER — ALERT REPORT",
        f"  Generated : {ts_str}",
        f"  Regime    : {market_regime}  {regime_emoji}   |   Alerts : {total}",
        "═" * W,
    ]

    # Individual alert cards
    card_lines: List[str] = []
    for rank, alert in enumerate(all_alerts, start=1):
        card_lines.append("")
        card_lines.append(_build_alert_card(rank, total, alert))

    # Summary table
    table = "\n" + _build_summary_table(all_alerts)

    return "\n".join(header_lines + card_lines) + "\n" + table
